<?php require_once('../Connections/con3.php');
session_start();
require_once('../variables/variables.php');
$restrictGoTo = "../unauthorized.php";

if (!isset($_SESSION['username'])){   
 
  header("Location: ". $restrictGoTo); 
  exit;
}

if (!($_SESSION['User_Type'] == "IRB Staff")) { 
  
 if (!($_SESSION['User_Type'] == "IRB Chair")){
  header("Location: ". $restrictGoTo); 
  exit;
  }
}

function GetSQLValueString($theValue, $theType, $theDefinedValue = "", $theNotDefinedValue = "") 
{
  $theValue = (!get_magic_quotes_gpc()) ? addslashes($theValue) : $theValue;

  switch ($theType) {
    case "text":
      $theValue = ($theValue != "") ? "'" . $theValue . "'" : "NULL";
      break;    
    case "long":
    case "int":
      $theValue = ($theValue != "") ? intval($theValue) : "NULL";
      break;
    case "double":
      $theValue = ($theValue != "") ? "'" . doubleval($theValue) . "'" : "NULL";
      break;
    case "date":
      $theValue = ($theValue != "") ? "'" . $theValue . "'" : "NULL";
      break;
    case "defined":
      $theValue = ($theValue != "") ? $theDefinedValue : $theNotDefinedValue;
      break;
  }
  return $theValue;
}

$editFormAction = $_SERVER['PHP_SELF'];
if (isset($_SERVER['QUERY_STRING'])) {
  $editFormAction .= "?" . htmlentities($_SERVER['QUERY_STRING']);
}

if ((isset($_POST["MM_update"])) && ($_POST["MM_update"] == "form1")) {
$today=date("m/d/y H:i:s");
$comComments=$_POST['prev_comments']."<br><br>".$today." ".$_SESSION['username'].":<br>".$_POST['comments'];


	 $newaction=$_POST['irbActionLog']."<br>".$today."  ".$_SESSION['username'].":<br>";
	 $newaction = $newaction." Email review results/comments to applicant.";

  $updateSQL = sprintf("UPDATE continuation SET appFinished=%s, irbActionLog=%s, Approval=%s, ApprovalDate=%s, Comments=%s WHERE ID=%s",
  				GetSQLValueString($_POST['appFinished'], "text"),
  						GetSQLValueString($newaction, "text"),
                       GetSQLValueString($_POST['Approval'], "text"),
                       GetSQLValueString($_POST['evaDate'], "text"),
                       GetSQLValueString($comComments, "text"),
                       GetSQLValueString($_POST['ID'], "text"));

  mysql_select_db($database_con3, $con3);
  $Result1 = mysql_query($updateSQL, $con3) or die(mysql_error());
  
    $updateSQL = sprintf("UPDATE application SET continuationID=%s, lastApprovalDate=%s WHERE App_Number=%s",
  				 GetSQLValueString($_POST['ID'], "text"),

                       GetSQLValueString($_POST['evaDate'], "text"),
                     
                       GetSQLValueString($_POST['appNum'], "text"));

  mysql_select_db($database_con3, $con3);
  $Result1 = mysql_query($updateSQL, $con3) or die(mysql_error());
  
 $to = $_POST['emailAdd'];	
 if ($_POST['Approval'] == "Yes"){

 $subject = "Continuation Request ".$_POST['ID']. " - Approval";

$body = "DO NOT REPLY TO THIS MESSAGE. This email message is generated by the IRB online application program.\r\r\nBased on the information in IRB Continuation Request ".$_POST['ID'].", your request is approved.\r\r\nIf you have questions, please submit an IRB Inquiry form:\r\r\nhttp://www.txstate.edu/research/irb/irb_inquiry.html"."\r\rComments:\r".$_POST['comments'];

$body = $body.$emailSig;

 }
 else{
 $subject = $_POST['subject'];

 $body = "IRB Application Continuation/Changes Request: ".$_POST['ID']."\r\rApproval? ".$_POST['Approval']."\rComments:\r".$_POST['comments'];
$body = $body.$emailSig;
  
}
mail($to,$subject,$body, $headers);
}
$id=$_GET['ID'];
mysql_select_db($database_con3, $con3);
$query_Recordset1 = "SELECT appFinished, continuation.App_Number, irbActionLog,continuation.Approval, continuation.ApprovalDate, continuation.Comments, username FROM continuation where ID='".$id."'";
$Recordset1 = mysql_query($query_Recordset1, $con3) or die(mysql_error());
$row_Recordset1 = mysql_fetch_assoc($Recordset1);
$totalRows_Recordset1 = mysql_num_rows($Recordset1);
$user = $row_Recordset1['username'];
$app = $row_Recordset1['App_Number'];

$today=date("m/d/y H:i:s");

mysql_select_db($database_con3, $con3);
$query_Recordset3 = "SELECT `user`.Email FROM `user` where username='".$user."'";
$Recordset3 = mysql_query($query_Recordset3, $con3) or die(mysql_error());
$row_Recordset3 = mysql_fetch_assoc($Recordset3);
$totalRows_Recordset3 = mysql_num_rows($Recordset3);
?>


<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
  <meta http-equiv="Content-Type"
 content="text/html; charset=iso-8859-1">
  <title>Texas State University-San Marcos | IRB Online Application</title>
  <LINK href="../irbstyle.css" rel="stylesheet" type="text/css">


  <style type="text/css">
<!--
.style42 {color: #FFFFFF}
.style43 {font-size: large}
-->
  </style></head>


<body>
<table width="800" border="0" align="center" cellpadding="0" cellspacing="0" bgcolor="#FFFFFF" >
  <tr><td>
<table width="100%" border="0" align="center" cellpadding="0" cellspacing="0" background="../tbbg.gif" >
<tbody>
   <tr background="tbbg.gif">
            <td valign="top"><p align="left" class="style6 style24"><img src="../banner2.jpg" height="160"></td>
            <td valign="middle" background="../tbbg.gif"><p align="center"> <a class="tsu" href="http://www.txstate.edu">Texas State University</a></p>
              <p align="center"><a class="irbhome" href="index.php" ><span class="style43">I</span>nstitutional <span class="style43">R</span>eview <span class="style43">B</span>oard <span class="style43">O</span>nline <span class="style43">A</span>pplication </p>
           </a>
          
            </span></td>
 
  </tr>
</tbody></table> 

</td></tr><tr><td valign="top">
<table width="100%" bgcolor="#FFFFFF" border="0">

 <tr bgcolor="#000000">
    <td bgcolor="#000000" align="center" colspan="4">
      <div align="center"><a href="../<?php echo $_SESSION['myhome'];?>" class="irb">My IRB Home</a></span> <span class="style42">|</span> <a href="irb_listContinuation.php" class="irb">List All Continuation/Change Application </a> <span class="style42">|</span> <a href="../LogOut.php" class="irb">Log Out</a><br>
        
      </div></td></tr>
		<tr><td colspan="4"> 
      <p align="center">&nbsp;</p>
      </td>
        </tr></table><tr><td>
<table width="812" border="0" cellpadding="5" cellspacing="0" bgcolor="#FFFFFF" align="center">
  <tr><td>

  <p align="center" class="style47"><span class="style49"><strong>APPLICATION FOR IRB CONTINUATION/CHANGE EVALUATION</strong></span><BR></p>
    <tr>
      <td valign="top">
      <table border="0" cellpadding="0" cellspacing="0" width="100%"><tr>
        <td>
          <p>Continuation Application ID: <?php echo $_GET['ID'];?>          </p>
          <p>IRB Application Number:   <?php echo $row_Recordset1['App_Number']; ?></p></td>
      </tr>
   </table></td></tr><tr><td><hr>
   <table>
   <form name="form1" action="<?php echo $editFormAction; ?>" method="POST">

<tr><td valign="top"><p align="left"><strong>
Approval?</strong>
<p align="left">
  <input name="Approval" type="radio" value="Yes" <?php if ($row_Recordset1['Approval'] == "Yes") echo checked; ?>> 
  Yes
<p align="left">
<input name="Approval" type="radio" value="No" <?php if ($row_Recordset1['Approval'] == "No") echo checked; ?>>
No</p></td>
<td valign="top"><strong>IRB Evaluation Finished?</strong>
  <p align="left"> <input name="appFinished" type="radio" value="Yes" <?php if ($row_Recordset1['appFinished'] == "Yes") echo checked; ?>> 
  Yes
<p align="left">
<input name="appFinished" type="radio" value="No" <?php if ($row_Recordset1['appFinished'] == "No") echo checked; ?>>
No</p></td></tr>
<tr><td colspan="2"><hr>
<p align="left"><br>
  <strong>Previous Comments:</strong><br>
  <?php echo $row_Recordset1['Comments']; ?> 
  <input type="hidden" name="prev_comments" value="<?php echo $row_Recordset1['Comments']; ?>">
<p><hr><strong>Send New New Comments to Applicant<br>
</strong>
<br><br>
Subject: <input name="subject" type="text" value="<?php echo $_GET['ID']; ?>"><br><br>
  <textarea name="comments" cols="100" rows="8"></textarea>
  <input name="ID" type="hidden" value="<?php echo $_GET['ID'];?>">
  <input name="evaDate" type="hidden" value="<?php echo $today;?>">
  <input name="emailAdd" type="hidden" value="<?php echo $row_Recordset3['Email']; ?>">
  <input name="appNum" type="hidden" value="<?php echo $row_Recordset1['App_Number']; ?>">
    <input type="hidden" name="irbActionLog" ID="irbActionLog" value="<?php echo $row_Recordset1['irbActionLog'];?>">
<p align="left">
  <label>
  <input type="submit" name="Submit" value="Send Comments and Evaluation Results">
  <br>
  <span class="style17">*</span>Click &quot;Submit&quot; button only once to avoid receiving multiple email messages. </label>
  <input type="hidden" name="MM_update" value="form1">
   </td></tr></form></table><tr><td><br><br><table style="width: 100%;" border="0" cellpadding="0" cellspacing="0">
           
                <tr>
                  <td><hr></td>
                </tr>
             
    <tr>
      <td style="vertical-align: top; height: 60px;"><?php include("../footer.php"); ?></td>
    </tr>
</table>	
</td></tr></table>
   
  <?php
mysql_free_result($Recordset1);



mysql_free_result($Recordset3);
?>
   
