<?php require_once('../Connections/con3.php'); 
require_once('../variables/variables.php');
session_start();
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
  <title>Texas State University-San Marcos | IRB Online Application</title>
  <LINK href="../irbstyle.css" rel="stylesheet" type="text/css">
  <style type="text/css">
<!--
.style42 {color: #FFFFFF}
.style43 {font-size: large}
-->
  </style>
  </head>
<?php
$restrictGoTo = "../unauthorized.php";

if (!isset($_SESSION['username'])){   
 
  header("Location: ". $restrictGoTo); 
  exit;
}
$expNum = mt_rand(0000, 10000);
 
$expNum = chr(rand(65,90)).$expNum;
$expNum= "EXP".date("Y").$expNum;

function GetSQLValueString($theValue, $theType, $theDefinedValue = "", $theNotDefinedValue = "") 
{
  $theValue = (!get_magic_quotes_gpc()) ? addslashes($theValue) : $theValue;

  switch ($theType) {
    case "text":
      $theValue = ($theValue != "") ? "'" . $theValue . "'" : "NULL";
      break;    
    case "long":
    case "int":
      $theValue = ($theValue != "") ? intval($theValue) : "NULL";
      break;
    case "double":
      $theValue = ($theValue != "") ? "'" . doubleval($theValue) . "'" : "NULL";
      break;
    case "date":
      $theValue = ($theValue != "") ? "'" . $theValue . "'" : "NULL";
      break;
    case "defined":
      $theValue = ($theValue != "") ? $theDefinedValue : $theNotDefinedValue;
      break;
  }
  return $theValue;
}

$editFormAction = $_SERVER['PHP_SELF'];
$today=date("m/d/y H:i:s");
if (isset($_SERVER['QUERY_STRING'])) {
  $editFormAction .= "?" . htmlentities($_SERVER['QUERY_STRING']);
}

if ((isset($_POST["MM_insert"])) && ($_POST["MM_insert"] == "irb_exemption_form")) 
    {

$errmsg = "";
   
   if(trim($_POST['sponsorship']) =="" )
   {
      $errmsg = $errmsg.'Section I, Question 1 is required\r';
   } 
   if(trim($_POST['II_1_academic_project']) =="" )
   {
      $errmsg = $errmsg. 'Section II, Question 1 is required\r';
	
	  
   } 
   if(trim($_POST['II_2_contribute_knowledge']) =="")
   {
      $errmsg = $errmsg.'Section II, Question 2 is required\r';
	    
	}
   
     if(trim($_POST['II_3_share_results']) =="" )
   {
      $errmsg = $errmsg.'Section II, Question 3 is required\r';
	   
	}
   
     if(trim($_POST['II_4_interact_people']) =="" )
   {
      $errmsg = $errmsg.'Section II, Question 4 is required\r';
	     
	}
	
	    if(trim($_POST['II_5_collect_info']) =="" ){
      
      $errmsg = $errmsg.'Section II, Question 5 is required\r';
	   
	}
	 if($_POST['II_6_involve_pregnant']=="")
	 	$errmsg = $errmsg.'Section II, Question 6 is required\r';
     if($_POST['II_7_involve_prisoners']=="")
		$errmsg = $errmsg.'Section II, Question 7 is required\r';
     if($_POST['II_8_involve_vulnerable']=="")
	 $errmsg = $errmsg.'Section II, Question 8 is required\r';
     if($_POST['II_9_medical_identifiers']=="")
	 $errmsg = $errmsg.'Section II, Question 9 is required\r';
      if($_POST['II_10_minor_subjects']=="")
	  $errmsg = $errmsg.'Section II, Question 10 is required\r';
      if($_POST['II_11_FDAproduct_used']=="")
	  $errmsg = $errmsg.'Section II, Question 11 is required\r';
      if($_POST['II_12_ingest_substance']=="")
	  $errmsg = $errmsg.'Section II, Question 12 is required\r';
      if($_POST['II_13_physical_tasks']=="")
	  $errmsg = $errmsg.'Section II, Question 13 is required\r';
      if($_POST['II_14_influence_behavior']=="")
	  $errmsg = $errmsg.'Section II, Question 14 is required\r';
      if($_POST['II_15_sensitive_discussion']=="")
	  $errmsg = $errmsg.'Section II, Question 15 is required\r';
      if($_POST['II_16_exposeto_discomfort']=="")
	  $errmsg = $errmsg.'Section II, Question 16 is required\r';
      if($_POST['II_17_subject_deception']=="")
	  $errmsg = $errmsg.'Section II, Question 17 is required\r';
      if($_POST['II_18_taping_subjects']=="")
	  $errmsg = $errmsg.'Section II, Question 18 is required\r';
      if(trim($_POST['III_1_exempt_category'])=="")
	  $errmsg = $errmsg.'Section III, Question 1 is required\r';
     if(trim($_POST['III_2_project_purpose'])=="")
	 $errmsg = $errmsg.'Section III, Question 2 is required\r';
      if(trim($_POST['III_3_category_pertains'])=="")
	  $errmsg = $errmsg.'Section III, Question 3 is required\r';
      if(trim($_POST['III_4_exempt_reason'])=="")
	  $errmsg = $errmsg.'Section III, Question 4 is required\r';

      if (strlen($errmsg)>1) {


//echo "<font color='red'>Following errors occured:</font><br>".$errmsg;
?>
<script language="JavaScript">
alert("<?php echo $errmsg;?>");
</script>
<?php
include "irb_exemption_back.php";
}
else{

$to = $_SESSION['Email'];

	$body = "DO NOT REPLY TO THIS MESSAGE. This email message is generated by the IRB online application program.\r\rYour Exemption Request has been submitted for review. Application number: ".$_POST['expNum'].". While under review, your application is locked but is available as read-only.  You may log into the IRB application module at any time to monitor review status. You will receive notification emails when your application status changes. \r\rIf you have questions, please submit an IRB Inquiry form: \rhttp://www.txstate.edu/research/irb/irb_inquiry.html\r\r";

    $body = $body.$emailSig;
	$subject = "Confirmation: Exemption Request ". $_POST['expNum']." submitted for review";

	mail($to,$subject,$body, $headers); 
	
	//inform OSP
	mysql_select_db($database_con3, $con3);
$query_Recordset1 = "SELECT Email FROM user where User_Type='IRB Staff'";
$Recordset1 = mysql_query($query_Recordset1, $con3) or die(mysql_error());
$row_Recordset1 = mysql_fetch_assoc($Recordset1);
$totalRows_Recordset1 = mysql_num_rows($Recordset1);
	
	$irbEmail=$row_Recordset1['Email'];
	$subject = "IRB Exemption Request Submitted: ". $_POST['expNum'];
	$body = "DO NOT REPLY TO THIS MESSAGE. This email message is generated by the IRB online application program.\r\rAn IRB Exemption Request has been submitted. Application number: ".$_POST['expNum'].".";
	$body = $body.$emailSig;
	mail($irbEmail,$subject,$body, $headers); 
	$approval = "Not Yet";
	$appFinished = "No";
  $insertSQL = sprintf("INSERT INTO exemption (appFinished,expNum, SenderStatus, sponsorship, FacultyName, academic_project, contribute_knowledge, share_results, interact_people, collect_info, involve_pregnant, involve_prisoners, involve_vulnerable, medical_identifiers, minor_subjects, FDAproduct_used, ingest_substance, physical_tasks, influence_behavior, sensitive_discussion, exposeto_discomfort, subject_deception, taping_subjects, exempt_category, project_purpose, category_pertains, exempt_reason, ReceiveDate, username, Approval) VALUES (%s,%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)",
						GetSQLValueString($appFinished, "text"),
  						GetSQLValueString($_POST['expNum'], "text"),
                       GetSQLValueString($_POST['SenderStatus'], "text"),
                       GetSQLValueString($_POST['sponsorship'], "text"),
                       GetSQLValueString($_POST['FacultyName'], "text"),
                       GetSQLValueString($_POST['II_1_academic_project'], "text"),
                       GetSQLValueString($_POST['II_2_contribute_knowledge'], "text"),
                       GetSQLValueString($_POST['II_3_share_results'], "text"),
                       GetSQLValueString($_POST['II_4_interact_people'], "text"),
                       GetSQLValueString($_POST['II_5_collect_info'], "text"),
                       GetSQLValueString($_POST['II_6_involve_pregnant'], "text"),
                       GetSQLValueString($_POST['II_7_involve_prisoners'], "text"),
                       GetSQLValueString($_POST['II_8_involve_vulnerable'], "text"),
                       GetSQLValueString($_POST['II_9_medical_identifiers'], "text"),
                       GetSQLValueString($_POST['II_10_minor_subjects'], "text"),
                       GetSQLValueString($_POST['II_11_FDAproduct_used'], "text"),
                       GetSQLValueString($_POST['II_12_ingest_substance'], "text"),
                       GetSQLValueString($_POST['II_13_physical_tasks'], "text"),
                       GetSQLValueString($_POST['II_14_influence_behavior'], "text"),
                       GetSQLValueString($_POST['II_15_sensitive_discussion'], "text"),
                       GetSQLValueString($_POST['II_16_exposeto_discomfort'], "text"),
                       GetSQLValueString($_POST['II_17_subject_deception'], "text"),
                       GetSQLValueString($_POST['II_18_taping_subjects'], "text"),
                       GetSQLValueString($_POST['III_1_exempt_category'], "text"),
                       GetSQLValueString($_POST['III_2_project_purpose'], "text"),
                       GetSQLValueString($_POST['III_3_category_pertains'], "text"),
                       GetSQLValueString($_POST['III_4_exempt_reason'], "text"),
					   GetSQLValueString($today, "text"),
					   GetSQLValueString($_SESSION['username'], "text"),
					   GetSQLValueString($approval, "text")
					   );

  mysql_select_db($database_con3, $con3);
  $Result1 = mysql_query($insertSQL, $con3) or die(mysql_error());
mysql_free_result($Recordset1);
  //$insertGoTo = "../applicant_home.php";


  ?>

<body>
<table width="800" border="0" align="center" cellpadding="0" cellspacing="0" bgcolor="#FFFFFF" >
  <tr><td>
<table width="100%" border="0" align="center" cellpadding="0" cellspacing="0" background="../tbbg.gif" >
<tbody>
   <tr background="tbbg.gif">
            <td valign="top"><p align="left" class="style6 style24"><img src="../banner2.jpg" height="160"></td>
            <td valign="middle" background="../tbbg.gif"><p align="center">  <a class="tsu" href="http://www.txstate.edu">Texas State University</a></p>
              <p align="center"><a class="irbhome" href="index.php" ><span class="style43">I</span>nstitutional <span class="style43">R</span>eview <span class="style43">B</span>oard <span class="style43">O</span>nline <span class="style43">A</span>pplication </p>
           </a>
          
            </span></td>
 
  </tr>
</tbody></table> 

</td></tr><tr><td><table width="100%" bgcolor="#FFFFFF" border="0">

 <tr>
    <td bgcolor="#000000" align="center">
   <a href="../<?php echo $_SESSION['myhome'];?>" class="irb">My IRB Home</a></span> <span class="style42">|</span> <a href="../LogOut.php" class="irb">Log Out</a><br>
     
      </td></tr>
		<tr><td> 
      <p align="center">&nbsp;</p>
      <p align="center"><?php echo $_SESSION['name'];?></p></td>
        </tr>
<?php
 echo "<td>IRB exemption application submission received. A confirmation message has been sent to you. Your application reference number: <font color='red'>".$_POST['expNum']."</font>. Your Exemption Request has been submitted for review. While under review, your application is locked but is available as read-only.  You may log into the IRB application system at any time to monitor review status. <br><br><br></td></tr>";
 
 ?>
 <tr><td>
<table style="width: 100%;" border="0" cellpadding="0" cellspacing="0">
           
                <tr>
                  <td><br><hr></td>
                </tr>
             
    <tr>
      <td style="vertical-align: top; height: 60px;"><?php include("../footer.php"); ?></td>
    </tr>
</table>
<?php

  }
    }
else{
?> 

<body>
<table width="800" border="0" align="center" cellpadding="0" cellspacing="0" bgcolor="#FFFFFF" >
  <tr><td>
<table width="100%" border="0" align="center" cellpadding="0" cellspacing="0" background="../tbbg.gif" >
<tbody>
   <tr background="tbbg.gif">
            <td valign="top"><p align="left" class="style6 style24"><img src="../banner2.jpg" height="160"></td>
            <td valign="middle" background="../tbbg.gif"><p align="center"> <a class="tsu" href="http://www.txstate.edu">Texas State University</a></p>
              <p align="center"><a class="irbhome" href="index.php" ><span class="style43">I</span>nstitutional <span class="style43">R</span>eview <span class="style43">B</span>oard <span class="style43">O</span>nline <span class="style43">A</span>pplication </p>
           </a>
          
            </span></td>
 
  </tr>
</tbody></table> 

</td></tr><tr><td><table width="100%" bgcolor="#FFFFFF" border="0">

 <tr>
    <td bgcolor="#000000" align="center">
   <a href="../<?php echo $_SESSION['myhome'];?>" class="irb">My IRB Home</a></span> <span class="style42">|</span> <a href="../LogOut.php" class="irb">Log Out</a><br>      </td></tr>
		<tr><td> 
      <p align="center">&nbsp;</p>
      <p align="center"><?php echo $_SESSION['name'];?></p></td>
        </tr>
      </strong></div>
 <tr><td>
     <h5 align="center"><p>APPLICATION FOR IRB EXEMPTION </h5>
     <p>This is your IRB Exemption Application Number: <font color="#CC0033"><?php echo $expNum;?></font></p><hr />
<form action="<?php echo $editFormAction; ?>" method="POST" name="irb_exemption_form" id="irb_exemption_form" >

  <input type="hidden" name="expNum" value="<?php echo $expNum;?>" />

  
    <h5>Section I </h5>
    
      <font color = "red"> Classroom exemption instructions:
        
      </font><ul>
      <li><font color = "red"> For undergraduate classroom projects only, a single application for each separate class, submitted by the faculty member, is required to establish exemption for multiple student projects, if the following conditions apply: </font></li>

      <li><font color = "red">The faculty member has a current completion certificate for the CITI Course in Human Subjects Protection.</font></li>

      <li><font color = "red">The faculty member takes responsibility for ensuring all student interactions with human subjects meet the standards for exemption, and if individual projects do not meet the standards for exemption, the students should submit a regular IRB application.</font></li>

      <li><font color = "red">The faculty member acknowledges that exemption status has no bearing on the need for informed consent and that if informed consent procedures are necessary, ensures they will be carried out in accordance with the Texas State IRB consent form checklist. </font></li>
  
      <li><font color = "red">The faculty member submits one exemption request per class and only for their own classes.</font></li>
    </ul>
    <font color = "red">
        <P>
          
          NOTE: If this application is for an undergraduate classroom exemption "Academic/Classroom Project" must be selected from the drop-down list for question 1.         
        <hr>
          </font>
             <br> 
      </li>
    </ul>
    </td></tr>
    <tr>
      <td>1.&nbsp; This project is&nbsp;
        <label for="label"></label>
        <select name="sponsorship" id="sponsorship">
          <option value="" selected="selected">--select one--</option>
          <option value="Funded Research">Funded Research</option>
          <option value="Other Sponsored Program/Contract">Other Sponsored Program/Contract</option>
          <option value="FACULTY non-funded Research">FACULTY non-funded Research</option>
          <option value="Thesis/Dissertation">Thesis/Dissertation</option>
          <option value="Academic/Classroom Project">Academic/Classroom Project</option>
          <option value="Institutional/Admin Program">Institutional/Admin Program</option>
          <option value="Other">Other</option>
        </select></td>
    </tr>
    <tr>
      <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </td>
    </tr>
    <tr>
      <td>2.&nbsp; If you are a student, please provide your supervising faculty member's full name: </td>
    </tr>
    <tr>
      <td>&nbsp;&nbsp;&nbsp;&nbsp; Faculty Name (N/A, if not a student)
        <input name="FacultyName" type="text" id="FacultyName" value="" size="35" /></td>
    </tr>
    <tr>
      <td><h5><br>
        Section II </h5></td>
    </tr>
    <tr>
      <td>1.&nbsp; If this is  an academic or classroom project, does the scope extend beyond Texas State University? </td>
    </tr>
    <tr>
      <td>&nbsp;
      <label>
          <input name="II_1_academic_project" type="radio" value="Yes" />
Yes</label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<label>
<input name="II_1_academic_project" type="radio" value="No" />
No</label>      </td>
    </tr>
    <tr>
      <td>2.&nbsp; Would you describe this project as &quot;a systematic investigation, designed to develop or contribute to generalizable knowledge? </td>
    </tr>
    <tr>
      <td>&nbsp;
          <label>
          <input name="II_2_contribute_knowledge" type="radio" value="Yes" />
Yes</label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<label>
<input name="II_2_contribute_knowledge" type="radio" value="No" />
No</label>      </td>
    </tr>
    <tr>
      <td>3.&nbsp; Will the results of your project be put on the internet, shared at a conference, published, or otherwise disseminated? </td>
    </tr>
    <tr>
      <td>&nbsp;
          <label>
<input name="II_3_share_results" type="radio" value="Yes" /> 
Yes</label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<label>
<input name="II_3_share_results" type="radio" value="No" />
No</label>      </td>
    </tr>
    <tr>
      <td>4.&nbsp;Will identifiable private information from individuals be collected from contact with research participants ? </td>
    </tr>
    <tr>
      <td>&nbsp;
          <label>
          <input name="II_4_interact_people" type="radio" value="Yes" />
Yes</label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<label>
<input name="II_4_interact_people" type="radio" value="No" />
No</label>      </td>
    </tr>
    <tr>
      <td>5.&nbsp; Will identifiable private information from individuals be collected from other sources (e.g. medical records)? </td>
    </tr>
    <tr>
      <td>&nbsp;
          <label>
          <input name="II_5_collect_info" type="radio" value="Yes" />
Yes</label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<label>
<input name="II_5_collect_info" type="radio" value="No" />
No</label>      </td>
    </tr>
    <tr>
      <td>6.&nbsp; Does the project involve fetuses, pregnant women or human in vitro fertilization? </td>
    </tr>
    <tr>
      <td>&nbsp;
          <label>
          <input name="II_6_involve_pregnant" type="radio" value="Yes" />
Yes</label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<label>
<input name="II_6_involve_pregnant" type="radio" value="No" />
No</label>      </td>
    </tr>
    <tr>
      <td>7.&nbsp; Does the project involve prisoners? </td>
    </tr>
    <tr>
      <td>&nbsp;
          <label>
          <input name="II_7_involve_prisoners" type="radio" value="Yes" />
Yes</label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<label>
<input name="II_7_involve_prisoners" type="radio" value="No" />
No</label>      </td>
    </tr>
    <tr>
      <td>8.&nbsp; Does the project involve any persons who are mentally impaired or homeless  or  who have limited autonomy? </td>
    </tr>
    <tr>
      <td>&nbsp;
          <label>
          <input name="II_8_involve_vulnerable" type="radio" value="Yes" />
Yes</label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<label>
<input name="II_8_involve_vulnerable" type="radio" value="No" />
No</label>      </td>
    </tr>
    <tr>
      <td>9.&nbsp; Does the project involve the review of medical records if the information is recorded in such a way that subjects can be indentified, directly or through identifiers linked to the subjects? </td>
    </tr>
    <tr>
      <td>&nbsp;
          <label>
<input name="II_9_medical_identifiers" type="radio" value="Yes" /> 
Yes</label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<label>
<input name="II_9_medical_identifiers" type="radio" value="No" />
No</label>      </td>
    </tr>
    <tr>
      <td>10. Does the project involve survey or interview techniques which include minors as subjects in which the researcher(s) participate in the activities being observed? </td>
    </tr>
    <tr>
      <td>&nbsp;
          <label>
          <input name="II_10_minor_subjects" type="radio" value="Yes" />
Yes</label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<label>
<input name="II_10_minor_subjects" type="radio" value="No" />
No</label>      </td>
    </tr>
    <tr>
      <td>11. Will a drug, biological product, medical device, or other product regulated by the FDA be used in this project? </td>
    </tr>
    <tr>
      <td>&nbsp;
          <label>
          <input name="II_11_FDAproduct_used" type="radio" value="Yes" />
Yes</label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<label>
<input name="II_11_FDAproduct_used" type="radio" value="No" />
No</label>      </td>
    </tr>
    <tr>
      <td>12. Will the participants be asked to ingest substances of any kind?</td>
    </tr>
    <tr>
      <td>&nbsp;
          <label>
          <input name="II_12_ingest_substance" type="radio" value="Yes" />
Yes</label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<label>
<input name="II_12_ingest_substance" type="radio" value="No" />
No</label>      </td>
    </tr>
    <tr>
      <td>13. Will the participants be asked to perform any physical tasks? </td>
    </tr>
    <tr>
      <td>&nbsp;
          <label>
          <input name="II_13_physical_tasks" type="radio" value="Yes" />
Yes</label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<label>
<input name="II_13_physical_tasks" type="radio" value="No" />
No</label>      </td>
    </tr>
    <tr>
      <td>14. Does the research attempt to influence or change participants' behavior, perception, or cognition? </td>
    </tr>
    <tr>
      <td>&nbsp;
          <label>
          <input name="II_14_influence_behavior" type="radio" value="Yes" />
Yes</label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<label>
<input name="II_14_influence_behavior" type="radio" value="No" />
No</label>      </td>
    </tr>
    <tr>
      <td>15. Does the project involve questions or discussions of sensitive or deeply personal aspects of the subject's behavior, life experiences or attitudes?&nbsp; Examples include substance abuse, sexual activity, sexual orientation, sexual abuse, criminal behavior, sensitive demographic data, detailed health history, etc. </td>
    </tr>
    <tr>
      <td>&nbsp;
          <label>
          <input name="II_15_sensitive_discussion" type="radio" value="Yes" />
Yes</label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<label>
<input name="II_15_sensitive_discussion" type="radio" value="No" />
No</label>      </td>
    </tr>
    <tr>
      <td>16. Does the project involve techniques which expose the subject to discomfort, harassment, embarrassment, stigma, alarm or fear beyond levels encountered in the daily life of a healthy individual? </td>
    </tr>
    <tr>
      <td>&nbsp;
          <label>
          <input name="II_16_exposeto_discomfort" type="radio" value="Yes" />
Yes</label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<label>
<input name="II_16_exposeto_discomfort" type="radio" value="No" />
No</label>      </td>
    </tr>
    <tr>
      <td>17. Does the project involve the deception of subjects? </td>
    </tr>
    <tr>
      <td>&nbsp;
          <label>
          <input name="II_17_subject_deception" type="radio" value="Yes" />
Yes</label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<label>
<input name="II_17_subject_deception" type="radio" value="No" />
No</label>      </td>
    </tr>
    <tr>
      <td>18. Does the project involve videotaping or audiotaping of subjects? </td>
    </tr>
    <tr>
      <td>&nbsp;
          <label>
          <input name="II_18_taping_subjects" type="radio" value="Yes" />
Yes</label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<label>
<input name="II_18_taping_subjects" type="radio" value="No" />
No</label>      </td>
    </tr>
    <tr>
      <td><h5><br>
        Section III </h5></td>
    </tr>
    <tr>
      <td><a name="SectionIIIQuestion2" id="SectionIIIQuestion2"></a>1.&nbsp; If you are choosing one of the <a href="#categories_of_exemption">six federal categories of exemption</a>, which <strong>one</strong> are you choosing?<br />
        <span class="style9">**</span>If your project falls under more than one exemption, choose the one that is most applicable.&nbsp; You may cite the others in #3 below. </td>
    </tr>
    <tr>
      <td>&nbsp;&nbsp;&nbsp;&nbsp;
        <label>
        <select name="III_1_exempt_category" id="III_1_exempt_category">
          <option value="" selected="selected">--select one--</option>
          <option value="Category 1 (i)">Category 1 (i)</option>
          <option value="Category 1 (ii)">Category 1 (ii)</option>
          <option value="Category 2">Category 2</option>
          <option value="Category 3 (i)">Category 3 (i)</option>
          <option value="Category 3 (ii)">Category 3 (ii)</option>
          <option value="Category 4">Category 4</option>
          <option value="Category 5 (i)">Category 5 (i)</option>
          <option value="Category 5 (ii)">Category 5 (ii)</option>
          <option value="Category 5 (iii)">Category 5 (iii)</option>
          <option value="Category 5 (iv)">Category 5 (iv)</option>
          <option value="Category 6 (i)">Category 6 (i)</option>
          <option value="Category 6 (ii)">Category 6 (ii)</option>
        </select>
      </label></td>
    </tr>
    <tr>
      <td> <strong>Please note for questions 2, 3, and 4
        :&nbsp; The text areas are  limited to 2000 characters/approximately 300 words.&nbsp; Even though you are allowed to type more than the specified limit, those additional words/characters will be cropped/cut off when you move to the next question.</strong></td>
    </tr>
    <tr>
      <td>2.&nbsp; What is the purpose of the project? (300 words or less)</td>
    </tr>
    <tr>
      <td>&nbsp;&nbsp;&nbsp;&nbsp; <label>
        <textarea name="III_2_project_purpose" cols="100" rows="10" id="III_2_project_purpose" onchange="checkInputSize(this, 2000)"></textarea>
      </label></td>
    </tr>
    <tr>
      <td>3.&nbsp; Explain how this exemption category pertains to your project: (300 words or less) </td>
    </tr>
    <tr>
      <td><label>
      &nbsp;&nbsp;&nbsp;&nbsp;
      <textarea name="III_3_category_pertains" cols="100" rows="10" id="III_3_category_pertains" onchange="checkInputSize(this, 2000)"></textarea>
      </label></td>
    </tr>
    <tr>
      <td>4.&nbsp; If you believe your project poses no risk to human participants or should be exempt from IRB review for other reasons, please explain: (300 words or less) </td>
    </tr>
    <tr>
      <td>&nbsp;&nbsp;&nbsp;&nbsp; <label>
        <textarea name="III_4_exempt_reason" cols="100" rows="10" id="III_4_exempt_reason" onchange="checkInputSize(this, 2000)" ></textarea>
      </label></td>
    </tr>
    <tr>
      <td><div align="center">
	   <input type="hidden" name="username" value="<?php echo $_SESSION['username'];?>" />
        <input type="submit" name="submit" value="Submit Application" />
      </div></td>
    </tr>
   <tr><td><hr></td></tr>
  </table>
    <input type="hidden" name="MM_insert" value="irb_exemption_form">
</form>
<table width="100%" border="0" cellspacing="0" cellpadding="5">
  <tr>
    <td><h5><a name="categories_of_exemption" id="CategoriesofExemption"></a>Categories of Exemption:&nbsp;&nbsp; (<a href="#SectionIIIQuestion2">Return to Section III, Question 2</a>) 
    </h5>
    <p>Exempt Categories of Research listed at 45 CFR, Part 46, Sec. 101(b)<br />
        <br />
        (1) Research conducted in established or commonly accepted educational settings, involving normal educational practices, such as</p>
      <blockquote>
        <p>(i) research on regular and special education instructional strategies, or </p>
        <p>(ii) research on the effectiveness of or the comparison among instructional techniques, curricula, or classroom management methods.</p>
      </blockquote>
      2) Research involving the use of educational tests (cognitive, diagnostic, aptitude, achievement), survey procedures, interview procedures or observation of public behavior, unless:
      <blockquote>
        <p>(i) information obtained is recorded in such a manner that human subjects can be identified, directly or through identifiers linked to the subjects; and </p>
        <p>(ii) any disclosure of the human subjects' responses outside the research could reasonably place the subjects at risk of criminal or civil liability or be damaging to the subjects' financial standing, employability, or reputation.</p>
      </blockquote>
      <p >(<span class="style7">Please note</span>: Surveys on sensitive or personal topics which may cause stress to study participants may not be exempt from IRB review.)</p>
      <p >(<span class="style7">Note</span>: The section of this category pertaining to standardized educational tests may be applied to research involving children. This category may also apply to research with children when the investigator observes public behavior but does NOT participate in that behavior or activity. However this  section is NOT applicable to survey or interview research involving children.)</p>
      (3) Research involving the use of educational tests (cognitive, diagnostic, aptitude, achievement), survey procedures, interview procedures, or observation of public behavior that is not exempt under paragraph (2) of this section, if:
      <blockquote>
        <p>(i) the human subjects are elected or appointed public officials or candidates for public office; or </p>
        <p>(ii) federal statute(s) require(s) without exception that the confidentiality of the personally identifiable information will be maintained throughout the research and thereafter.</p>
      </blockquote>
      (4) Research involving the collection or study of existing data, documents, records, pathological specimens, or diagnostic specimens, if these sources are publicly available or if the information is recorded by the investigator in such a manner that subjects cannot be identified, directly or through identifiers linked to the subjects.
      <p >(Example: existing data, records review, pathological specimens)</p>
      <p >(<span class="style7">Note</span>: This data must be in existence before the project begins)</p>
      (5) Research and demonstration projects which are conducted by or subject to the approval of department or agency heads, and which are designed to study, evaluate, or otherwise examine:
      <blockquote>
        <p>(i) Public benefit or service programs;</p>
        <p><span >(ii) procedures for obtaining benefits or services under those programs;</span></p>
        <p> <span >(iii) possible changes in or alternatives to those programs or procedures; or</span></p>
        <p> <span >(iv) possible changes in methods or levels of payment for benefits or services under those programs.</span></p>
        <p>(<span class="style7">Note</span>: Exemption category refers to federal government research)</p>
      </blockquote>
      <p >(6) Taste and food quality evaluation and consumer acceptance studies.</p>
      <blockquote>
        <p>(i)&nbsp; if wholesome foods without additives are consumed or </p>
        <p>(ii) if a food is consumed that contains a food ingredient at or below the level and for a use found to be safe, or agricultural chemical or environmental contaminant at or below the level found to be safe, by the Food and Drug Administration or approved by the Environmental Protection Agency or the Food Safety and Inspection Service of the U.S. Department of Agriculture.</p>
      </blockquote>      <p class="formheading">&nbsp;</p></td>
  </tr>
</table>

<tr><td><br><br><table style="width: 100%;" border="0" cellpadding="0" cellspacing="0">
           
                <tr>
                  <td><hr></td>
                </tr>
             
    <tr>
      <td style="vertical-align: top; height: 60px;"><?php include("../footer.php"); ?></td>
    </tr>
</table>	
</td></tr></table>

</body>

<?php

}
?>
</html>
