<?php require_once('../Connections/con3.php');
session_start();
require_once('../variables/variables.php');
$restrictGoTo = "../unauthorized.php";

if (!isset($_SESSION['username'])){   
 
  header("Location: ". $restrictGoTo); 
  exit;
}

if ($_SESSION['User_Type'] != "IRB Staff"){
	if($_SESSION['User_Type'] != "IRB Chair") {   
 
 	 header("Location: ". $restrictGoTo); 
  		exit;
	}
}

function GetSQLValueString($theValue, $theType, $theDefinedValue = "", $theNotDefinedValue = "") 
{
  $theValue = (!get_magic_quotes_gpc()) ? addslashes($theValue) : $theValue;

  switch ($theType) {
    case "text":
      $theValue = ($theValue != "") ? "'" . $theValue . "'" : "NULL";
      break;    
    case "long":
    case "int":
      $theValue = ($theValue != "") ? intval($theValue) : "NULL";
      break;
    case "double":
      $theValue = ($theValue != "") ? "'" . doubleval($theValue) . "'" : "NULL";
      break;
    case "date":
      $theValue = ($theValue != "") ? "'" . $theValue . "'" : "NULL";
      break;
    case "defined":
      $theValue = ($theValue != "") ? $theDefinedValue : $theNotDefinedValue;
      break;
  }
  return $theValue;
}

$editFormAction = $_SERVER['PHP_SELF'];
if (isset($_SERVER['QUERY_STRING'])) {
  $editFormAction .= "?" . htmlentities($_SERVER['QUERY_STRING']);
}

if ((isset($_POST["MM_update"])) && ($_POST["MM_update"] == "form1")) {
$today=date("m/d/y H:i:s");
if ($_POST['comments']=="")
$_POST['comments'] ="No comments.";
$comComments=$_POST['prev_comments']."<br><BR>".$today."  ".$_SESSION['username'].":<br>".$_POST['comments'];

	 $newaction=$_POST['irbActionLog']."<br><BR>".$today."  ".$_SESSION['username'].":<br>";
	 $newaction = $newaction."IRB sent evaluation and/or comments/request to applicant.";

  $updateSQL = sprintf("UPDATE exemption SET appFinished=%s, irbActionLog=%s, Approval=%s, ApprovalDate=%s, Comments=%s WHERE expNum=%s",
  				GetSQLValueString($_POST['appFinished'], "text"),
  						GetSQLValueString($newaction, "text"),
                       GetSQLValueString($_POST['Approval'], "text"),
                       GetSQLValueString($_POST['evaDate'], "text"),
                       GetSQLValueString($comComments, "text"),
                       GetSQLValueString($_POST['expNum'], "text"));

  mysql_select_db($database_con3, $con3);
  $Result1 = mysql_query($updateSQL, $con3) or die(mysql_error());
  
 $to = $_POST['emailAdd'];	
// $subject = $_POST['subject'];
 if ($_POST['Approval'] == "Yes")
 {
 $subject = "Exemption Request ".$_POST['expNum']. " - Approval";

$body = "DO NOT REPLY TO THIS MESSAGE. This email message is generated by the IRB online application program.\r\r\nBased on the information in IRB Exemption Request ".$_POST['expNum']." which you submitted on ". $_POST['ReceiveDate'].", your project is exempt from full or expedited review by the Texas State Institutional Review Board.\r\r\nIf you have questions, please submit an IRB Inquiry form:\r\r\nhttp://www.txstate.edu/research/irb/irb_inquiry.html"."\r\rComments:\r".$_POST['comments'];

$body = $body.$emailSig;
}
else{
$subject = $_POST['subject'];
$body = $_POST['comments'].$emailSig;
}
	mail($to,$subject,$body, $headers);

 // $to = $_SESSION['Email'];
  //mail($to,$subject,$body, $headers);
  
  
}
$id=$_GET['expNum'];

$today=date("m/d/y H:i:s");

mysql_select_db($database_con3, $con3);
$query_Recordset4 = "SELECT username, appFinished, irbActionLog, exemption.Email, Approval, ApprovalDate, Comments, ReceiveDate FROM exemption where expNum ='".$id."'";
$Recordset4 = mysql_query($query_Recordset4, $con3) or die(mysql_error());
$row_Recordset4 = mysql_fetch_assoc($Recordset4);
$totalRows_Recordset4 = mysql_num_rows($Recordset4);
$app=$row_Recordset4['username'];

	mysql_select_db($database_con3, $con3);
$query_Recordset5 = "SELECT Email FROM user where username='".$app."'";
$Recordset5 = mysql_query($query_Recordset5, $con3) or die(mysql_error());
$row_Recordset5 = mysql_fetch_assoc($Recordset5);
$totalRows_Recordset5 = mysql_num_rows($Recordset5);
	
	$appEmail=$row_Recordset5['Email'];
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
  <meta http-equiv="Content-Type"
 content="text/html; charset=iso-8859-1">
  <title>Texas State University-San Marcos | IRB Online Application</title>
  <LINK href="../irbstyle.css" rel="stylesheet" type="text/css">


  <style type="text/css">
<!--
.style42 {color: #FFFFFF}
.style43 {font-size: large}
-->
  </style></head>


<body>
<table width="800" border="0" align="center" cellpadding="0" cellspacing="0" bgcolor="#FFFFFF" >
  <tr><td>
<table width="100%" border="0" align="center" cellpadding="0" cellspacing="0" background="../tbbg.gif" >

   <tr background="tbbg.gif">
            <td valign="top"><p align="left"><img src="../banner2.jpg" height="160"></td>
            <td valign="middle" background="../tbbg.gif"><p align="center"> <a class="tsu" href="http://www.txstate.edu">Texas State University</a></p>
              <p align="center"><a class="irbhome" href="index.php" ><span class="style43">I</span>nstitutional <span class="style43">R</span>eview <span class="style43">B</span>oard<br><span class="style43">O</span>nline <span class="style43">A</span>pplication</p>
           </a>
          
            </span></td>
 
  </tr>
</table> 

</td></tr><tr><td>
<table width="100%" bgcolor="#FFFFFF" border="0">

 <tr>
    <td align="center" bgcolor="#000000">
   <a href="../<?php echo $_SESSION['myhome'];?>" class="irb">My IRB Home</a></span><span class="style42"> |</span> <a href="irb_listExpApp.php" class="irb">All IRB Exemption Applications</a> <span class="style42">|</span><a href="irb_listExpApp_Notapproved.php" class="irb">Unapproved Applications</a><span class="style42">|</span><a href="../LogOut.php" class="irb">Log Out</a><br>      </td></tr>

       
    <tr>
      <td valign="top">
     
      <table border="0" cellpadding="0" cellspacing="0" width="100%"><tr>
        <td align="center"><span class="body"><p><br><strong>IRB EXEMPTION APPLICATION EVALUATION</strong></span></td></tr>
          </span>
          <TR><TD ><span class="body"><br><br>IRB Exemption Application Number</span>: <?php echo $id;?>                </td>
      </tr>
	          <TR><TD ><span class="body"><br><br>Submission Date</span>: <?php echo $row_Recordset4['ReceiveDate'];?>                </td>
      </tr>
   </table><table width="100%" bgcolor="#FFFFFF" border="0"> </td></tr>
   <form name="form1" action="<?php echo $editFormAction; ?>" method="POST">
   <tr><td>


<p align="left">Approval?
  
<p align="left">
  <input name="Approval" type="radio" value="Yes" <?php if ($row_Recordset4['Approval'] == "Yes") echo checked; ?>> 
  Yes
<p align="left">
<input name="Approval" type="radio" value="No" <?php if ($row_Recordset4['Approval'] == "No") echo checked; ?>>
No
 </td><td><br>IRB Evaluation Finished
  <p align="left"> <input name="appFinished" type="radio" value="Yes" <?php if ($row_Recordset4['appFinished'] == "Yes") echo checked; ?>> 
  Yes
<p align="left">
<input name="appFinished" type="radio" value="No" <?php if ($row_Recordset4['appFinished'] == "No") echo checked; ?>>
No</p></td>
   </tr><tr><td colspan="2">*If the exemption request is approved, an automatic message will be sent out when you click the "Send Comments and Evaluation Results" button. You can choose whether you want to add more comments or not bellow.</td></tr><tr><td colspan="2"><hr>
<p align="left"><strong>Last Evaluation/Comments Date:</strong> <?php echo $row_Recordset4['ApprovalDate'];?><br><br>
  <strong>Previous Comments</strong>
   <?php echo $row_Recordset4['Comments']; ?>
  <input type = "hidden" name="prev_comments" value="<?php echo $row_Recordset4['Comments']; ?>">
<hr><br><strong>Send New Comments to Applicant</strong><br><br>
Subject: <input name="subject" type="text" value="<?php echo $id; ?>"><br><br>
  Comments:<br><textarea name="comments" cols="80" rows="8"></textarea>
 <input name="ReceiveDate" type="hidden" value="<?php echo $row_Recordset4['ReceiveDate'];?>">
  <input name="evaDate" type="hidden" value="<?php echo $today;?>">
  <input name="emailAdd" type="hidden" value="<?php echo $appEmail; ?>">
  <input name="expNum" type="hidden" value="<?php echo $id; ?>">
   <input type="hidden" name="irbActionLog" ID="irbActionLog" value="<?php echo $row_Recordset4['irbActionLog'];?>">
<p align="left">
  <label>
  <input type="submit" name="Submit" value="Send Comments and Evaluation Results">
  <br>
  <span class="style44">*</span>  Click the &quot;Submit&quot; button only once to avoid the applicant receiving multiple email messages. </label>
  <input type="hidden" name="MM_update" value="form1">
</form>   </td>
    
   </tr></table>
   <tr><td><br><br><table style="width: 100%;" border="0" cellpadding="0" cellspacing="0">
           
                <tr>
                  <td><hr></td>
                </tr>
             
    <tr>
      <td style="vertical-align: top; height: 60px;"><?php include("../footer.php"); ?></td>
    </tr>
</table>

</td></tr></table>
   </body></html>
  <?php

mysql_free_result($Recordset4);
mysql_free_result($Recordset5);
?>
   
