<?php require_once('Connections/con3.php'); require_once('Connections/dbc.php');
session_start();
require_once('variables/variables.php');

$restrictGoTo = "unauthorized.php";

function GetSQLValueString($theValue, $theType, $theDefinedValue = "", $theNotDefinedValue = "") 
{
  $theValue = (!get_magic_quotes_gpc()) ? addslashes($theValue) : $theValue;

  switch ($theType) {
    case "text":
      $theValue = ($theValue != "") ? "'" . $theValue . "'" : "NULL";
      break;    
    case "long":
    case "int":
      $theValue = ($theValue != "") ? intval($theValue) : "NULL";
      break;
    case "double":
      $theValue = ($theValue != "") ? "'" . doubleval($theValue) . "'" : "NULL";
      break;
    case "date":
      $theValue = ($theValue != "") ? "'" . $theValue . "'" : "NULL";
      break;
    case "defined":
      $theValue = ($theValue != "") ? $theDefinedValue : $theNotDefinedValue;
      break;
  }
  return $theValue;
}


if (!isset($_SESSION['username'])){   
 
  header("Location: ". $restrictGoTo); 
  exit;
}


if (!($_SESSION['User_Type'] == "IRB Staff")) {   
 
  //header("Location: ". $restrictGoTo); 
 // exit;
//}

if (!($_SESSION['User_Type'] == "IRB Chair")) {   
 
  header("Location: ". $restrictGoTo); 
  exit;
}
}

 

 $appNum = $_GET['appNum'];

//***************************
if(isset($_POST['insert']) && $_POST['insert'] == "formInsert") 
 {
  $appNum = $_POST['appNum'];
  }
mysql_select_db($database_con3, $con3);
$query_Recordset1 = "SELECT application.App_Number, irbActionLog, username, Status, trainingFinished, application.rev1ID, application.rev2ID, application.rev3ID, trainingFinished FROM application where App_Number='".$appNum."'";
$Recordset1 = mysql_query($query_Recordset1, $con3) or die(mysql_error());
$row_Recordset1 = mysql_fetch_assoc($Recordset1);
$totalRows_Recordset1 = mysql_num_rows($Recordset1);
$noRev = 0;
 if ($row_Recordset1['rev1ID']) $noRev=1;
 if ($row_Recordset1['rev2ID']) $noRev=2;
 if ($row_Recordset1['rev3ID']) $noRev=3;
 if ($noRev==3)
 die("Three reviewers have been assigned to this application. You cannot assign more reviewers.");
 
  //****************************
  if ($noRev==2){
  $theValue1 = (!get_magic_quotes_gpc()) ? addslashes($row_Recordset1['rev1ID']) : $row_Recordset1['rev1ID'];
  $theValue2 = (!get_magic_quotes_gpc()) ? addslashes($row_Recordset1['rev2ID']) : $row_Recordset1['rev2ID'];
$query_Recordset3 = "SELECT `user`.username,`user`.FirstName, `user`.LastName,`user`.Department, `user`.User_Type FROM `user` WHERE (`user`.User_Type = 'reviewer' && (username != '".$theValue1."' && username != '".$theValue2."'))" ;
}
  if ($noRev==1){
  $theValue = (!get_magic_quotes_gpc()) ? addslashes($row_Recordset1['rev1ID']) : $row_Recordset1['rev1ID'];
$query_Recordset3 = "SELECT `user`.username,`user`.FirstName, `user`.LastName,`user`.Department, `user`.User_Type FROM `user` WHERE (`user`.User_Type = 'reviewer' && (username != '".$theValue."'))" ;

}
 if ($noRev==0)
$query_Recordset3 = "SELECT `user`.username,`user`.FirstName, `user`.LastName,`user`.Department, `user`.User_Type FROM `user` WHERE `user`.User_Type = 'reviewer'" ;

$Recordset3 = mysql_query($query_Recordset3, $con) or die(mysql_error());
$row_Recordset3 = mysql_fetch_assoc($Recordset3);
$totalRows_Recordset3 = mysql_num_rows($Recordset3);
 
 //****************************************************************
if(isset($_POST['insert']) && $_POST['insert'] == "formInsert") 
 {
  $appNum = $_POST['appNum'];
  $today=date("m/d/y H:i:s");
  $newaction=$_POST['irbActionLog']."<br>".$today."  ".$_SESSION['username'].":<br>Add a Reviewer to the application. The user ID of this reviewer is <em>". $_POST['userID']."</em>";
 
 $email1="";
 $email2="";
 $email3="";
if(trim($_POST['trainingFinished']) != "yes")
die("Applicant has not finished Human Subject Protection Training. You cannot submit the application to reviewers.");

$reviewerID=$_POST['userID'];

$query_Recordset2 = "SELECT `user`.Email FROM `user` WHERE `user`.username = '".$reviewerID."'";


$Recordset2 = mysql_query($query_Recordset2, $con) or die(mysql_error());
$row_Recordset2 = mysql_fetch_assoc($Recordset2);
$totalRows_Recordset2 = mysql_num_rows($Recordset2);


//===================================email applicant -- function removed as a result of last meeting
/*
$body = "\r\rThis email message is generated by the IRB online application program. Do not reply.\r\rAn IRB application has been sent to IRB reviewers for review. Should your application be deemed incomplete by IRB, you will receive another email requesting additional information and/or documents. The application number is: ". $_POST['appNum'];

 $to=$_POST['applicant'];
 $subject = "IRB Application ". $_POST['appNum'];
mail($to,$subject,$body);

*/

	//===============================================
	//mail($to,$subject,$body,$headers);


$i=$_POST['noRev'];
$str="Application Submitted to Reviewers for Review";
$today=date("m-d-y");
 $insertSQL="";

if ($i==2){

  $insertSQL = sprintf("UPDATE application SET irbActionLog=%s, Status = %s, rev3ID=%s WHERE App_Number=%s", GetSQLValueString($newaction, "text"),GetSQLValueString($str, "text"), GetSQLValueString($reviewerID, "text"), GetSQLValueString($_POST['appNum'], "text"));
}
 
 if ($i==1){
$str="Application Submitted to Reviewers for Review";

  $insertSQL = sprintf("UPDATE application SET irbActionLog=%s, Status = %s, rev2ID=%s WHERE App_Number=%s", GetSQLValueString($newaction, "text"),GetSQLValueString($str, "text"), GetSQLValueString($reviewerID, "text"), GetSQLValueString($_POST['appNum'], "text"));
}

 if ($i==0){
$str="Application Submitted to Reviewers for Review";

  $insertSQL = sprintf("UPDATE application SET irbActionLog=%s, Status = %s, ReviewDate = %s, rev1ID=%s WHERE App_Number=%s", GetSQLValueString($newaction, "text"),GetSQLValueString($str, "text"),GetSQLValueString($today, "text"), GetSQLValueString($reviewerID, "text"), GetSQLValueString($_POST['appNum'], "text"));
}
$Result1 = mysql_query($insertSQL, $con) or die(mysql_error());


//++++++++++++++++++++++++++email reviewers
 $subject = "Review IRB Application: ". $_POST['appNum'];
//$headers = "From: ospinfo@txstate.edu";
$body = "\r\rThis email message is generated by the IRB online application program. Do not reply.\r\rYou are assigned to evaluate a new IRB Application. The application number is ".$_POST['appNum'].". If you agree to review this application,  Please log into your IRB account to review the application:\r".$irbadd."\r\rIf you do not agree to review this application, please inform IRB chairs immediately.";
$body = $body.$emailSig;

	$to=$row_Recordset2['Email'];
////=============================
	mysql_free_result($Recordset2);
	$substring = "@txstate.edu"; 

if (strpos($to, $substring) !== false) {
   // Yes, '$substring' is found in '$string';
   mail($to,$subject,$body,$headers);
   header("Location: assignReviewer.php?appNum=".$appNum); 
 	exit;
} 
//else {
   //echo("The reviewer does not have a Texas State University email address. Click here to inform him/her that an IRB application has been assigned to him/her. <a href='mailto:".$to."' target='_blank'>Notice Reviewer</a>");
//}

	
}
//****************************************************************************


?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
  <meta http-equiv="Content-Type"
 content="text/html; charset=iso-8859-1">
  <title>Texas State University-San Marcos | IRB Online Application</title>
  <LINK href="irbstyle.css" rel="stylesheet" type="text/css">


  <style type="text/css">
<!--
.style43 {font-size: large}
-->
  </style>
</head>
<body>
<table width="800" border="0" align="center" cellpadding="0" cellspacing="0" bgcolor="#FFFFFF" >
  <tr><td>
<table width="800" border="0" align="center" cellpadding="0" cellspacing="0" background="tbbg.gif" >

   <tr background="tbbg.gif">
            <td width="552" valign="top"><p align="left" class="style6 style24"><img src="banner2.jpg" width="550" height="160"></td>
            <td width="248" valign="middle" background="tbbg.gif"><p align="center"> <a class="tsu" href="http://www.txstate.edu">Texas State University</a></p>
              <p align="center"><a class="irbhome" href="index.php" ><span class="style43">I</span>nstitutional <span class="style43">R</span>eview <span class="style43">B</span>oard <span class="style43">O</span>nline <span class="style43">A</span>pplication </p>
           
            </p>
            </span></td>
   </tr>
</table>
<table width="800" border="0" align="center" bgcolor="#ffffff">
          <tr>
            <td colspan="3" height="19" valign="top" bgcolor="#000000">
			  <div align="center"><span class="style46"><a href='osp_irb_home.php' class="irb">My IRB Home</a> </span><span class="style39">|</span><span class="style46"> <a href="appSummary_irb.php?appNum=<?php echo $appNum;?>" class="irb">Review Application Data</a> </span><span class="style39">|</span><span class="style46"> <a href="statSummary.php?appNum=<?php echo $appNum;?>" class="irb">Summary of Status, Evaluations and Action Logs</a></span><br>
			  <a href="assignReviewer.php?appNum=<?php echo $appNum;?>" class="irb">Assign/Change Reviewer(s)</a> </span><span class="style39">|</span><span class="style46"> <a href="irb_updatestatus.php?appNum=<?php echo $appNum;?>" class="irb"> Update Application Status</a> </span><span class="style39">|</span> <a href="irb_emailApp.php?appNum=<?php echo $appNum;?>" class="irb">Send Comments/Requests to Applicant </a> <span class="style39">|</span> <a href="LogOut.php" class="irb">Log Out</a> </div></td>
          </tr>

      </table>
      </td>
  </tr>
  <tr><td align="center"><div align="center" class="style3">
    <p>&nbsp;</p>
    <p>ADD A REVIEWER TO IRB APPLICATION</p>
  </div></td>
</tr>
<tr><td align="center" class="style49"><div align="center" class="style46">
  <p>&nbsp;</p>
  <p>Application Number: <?php echo $appNum;?>
    </p>
</div>
<tr><td class="style49">
<?php  if(isset($_POST['insert']) && $_POST['insert'] == "formInsert") 
{
$reviewerID=$_POST['userID'];

$query_Recordset2 = "SELECT `user`.Email FROM `user` WHERE `user`.username = '".$reviewerID."'";


$Recordset2 = mysql_query($query_Recordset2, $con) or die(mysql_error());
$row_Recordset2 = mysql_fetch_assoc($Recordset2);
$totalRows_Recordset2 = mysql_num_rows($Recordset2);
echo "<p><br>One reviewer added to the application, username: ".$_POST['userID'].", emaill address: ".$row_Recordset2['Email'].".<br><br>";

$substring = "@txstate.edu"; 

if (strpos($row_Recordset2['Email'], $substring) == false) {
   // '$substring' is not found in '$string';

   echo("<p>The reviewer does not have a Texas State University email address. Click Notice Reviewer to inform him/her that an IRB application has been assigned to him/her. <a href='mailto:".$row_Recordset2['Email']."?subject=Review IRB application: ".$appNum."'>Notice Reviewer</a>");
mysql_free_result($Recordset2);
}
}
?>


    <div align="center"></div></td></tr>

<tr>

<td align="center" bgcolor="#ffffff"><span class="style50"><p><br><strong>Select a Reviewer from the List: </strong></span>
  <p>
<form action="<?php echo $_SERVER['PHP_SELF'];?>" method="post">
<input name="appNum" type="hidden" value="<?php echo $appNum; ?>" />
<input name="irbActionLog" type="hidden" value="<?php echo $row_Recordset1['irbActionLog']; ?>" />
<input name="applicant" type="hidden" value="<?php echo $row_Recordset1['username']; ?>" />
<input name="trainingFinished" type="hidden" value="<?php echo $row_Recordset1['trainingFinished']; ?>" />
<select name="userID" id="userID" size = "5">
<?php 
do {  

        ?>           

  <option value="<?php echo $row_Recordset3['username']; ?>">
  <?php echo $row_Recordset3['LastName']; ?> 
  <?php echo $row_Recordset3['FirstName'].", "; ?>
    
  <?php echo $row_Recordset3['Department']; ?>
  
  <?php $theValue = (!get_magic_quotes_gpc()) ? addslashes($row_Recordset3['username']) : $row_Recordset3['username'];

$query_Recordset4 = "SELECT application.App_Number, application.ProjectTitle FROM application WHERE ((application.rev1ID = '".$theValue."' || application.rev2ID = '".$theValue."' || application.rev3ID = '".$theValue."') && (application.Status != 'Approved'))";
$Recordset4 = mysql_query($query_Recordset4, $con) or die(mysql_error());
$row_Recordset4 = mysql_fetch_assoc($Recordset4);
$totalRows_Recordset4 = mysql_num_rows($Recordset4);
echo "(".$totalRows_Recordset4. ")";
mysql_free_result($Recordset4);
?>
  </option>
<?php
} while ($row_Recordset3 = mysql_fetch_assoc($Recordset3))
?>
</select><p>

<input name="noRev" id="noRev" type="hidden" value="<?php echo $noRev;?>" />
<input name="submit" type="submit" value="Add Reviewer" />
<input name="insert" id="insert" type="hidden" value="formInsert" />
</form>
</p>        
            <table style="width: 100%;" border="0" cellpadding="0" cellspacing="0">
           
                <tr>
                  <td><hr></td>
                </tr>
             
    <tr>
      <td style="vertical-align: top; height: 60px;"><?php include("footer.php"); ?></td>
    </tr>
</table></td>
</tr></table>
</body>
</html>
<?php
mysql_free_result($Recordset1);

mysql_free_result($Recordset3);
//mysql_free_result($Recordset2);
?>
