<?php require_once('Connections/con3.php'); ?>
<?php
mysql_select_db($database_con3, $con3);
$query_Recordset1 = "SELECT `user`.Email, `user`.User_Type FROM `user` where User_Type='IRB Staff'";
$Recordset1 = mysql_query($query_Recordset1, $con3) or die(mysql_error());
$row_Recordset1 = mysql_fetch_assoc($Recordset1);
$totalRows_Recordset1 = mysql_num_rows($Recordset1);


  
	$to = $row_Recordset1['Email'];
//	$from = "From: ospinfo@txstate.edu";
	$body = "\r\rThis email message is generated by the IRB online application program. Do not reply.\r\rIRB Application submitted. Application number: ".$_POST['appNum'];
    
	$subject = "RE: IRB Application Submitted";

	mail($to,$subject,$body);
 // $to = $row_Recordset1['Email'];
//mail($to,$subject,$body);
  header("Location: ". $application_home.php); 
exit;


?>