<?php require_once('Connections/dbc.php');
session_start();

require_once('variables/variables.php');

$restrictGoTo = "unauthorized.php";

if (!isset($_SESSION['username'])){   
 
  header("Location: ". $restrictGoTo); 
  exit;
}


if (!($_SESSION['User_Type'] == "IRB Staff")) {   
 
  //header("Location: ". $restrictGoTo); 
 // exit;
//}

if (!($_SESSION['User_Type'] == "IRB Chair")) {   
 
  header("Location: ". $restrictGoTo); 
  exit;
}
}
?>

<?php
 function GetSQLValueString($theValue, $theType, $theDefinedValue = "", $theNotDefinedValue = "") 
{
  $theValue = (!get_magic_quotes_gpc()) ? addslashes($theValue) : $theValue;

  switch ($theType) {
    case "text":
      $theValue = ($theValue != "") ? "'" . $theValue . "'" : "NULL";
      break;    
    case "long":
    case "int":
      $theValue = ($theValue != "") ? intval($theValue) : "NULL";
      break;
    case "double":
      $theValue = ($theValue != "") ? "'" . doubleval($theValue) . "'" : "NULL";
      break;
    case "date":
      $theValue = ($theValue != "") ? "'" . $theValue . "'" : "NULL";
      break;
    case "defined":
      $theValue = ($theValue != "") ? $theDefinedValue : $theNotDefinedValue;
      break;
  }
  return $theValue;
}


$appNum = $_GET['appNum'];

//************* From posted *********************************
 if(isset($_POST['insert']) && $_POST['insert'] == "formInsert") 
 {

  $appNum = trim($_POST['appNum']);
  
  if (trim($_POST['reviewerAssigned'])=="yes")
  {
  echo "<a href='addReviewer.php?appNum=".$appNum."'>Add Reviewer</a><br>";
  die("You have assigned at least one reviewer assigned to this application. Please use 'Add Reviewer' tool to add more reviewers.");
  
  }

$today=date("m/d/y H:i:s");
  $newaction=$_POST['irbActionLog']."<br><br>".$today."  ".$_SESSION['username'].":<br>Assigned reviewer(s).";
 
 $email1="";
 $email2="";
 $email3="";
 
if (!(trim(strtoupper(trim($_POST['trainingFinished']))) == "YES")){

die("Applicant has not finished Human Subject Protection Training. You cannot submit the application to reviewers. <a href='javascript:history.back()'>Back</a>");
}

if(trim($_POST['Status']) == "Approved")
die("The application has been approved. You cannot make any changes on the revieweres.");

 $c=count($_POST['userID']);
if($c==0){ 
die("You have to at least select one reviewer from the list. <a href='javascript:history.back()'>Back</a>");
	}

 if($c==1){
 /*
 die("You need to select at least two reviewers for the application.");
 */
//$newaction = $newaction .$_POST['userID'][0];
$appquery = "SELECT `user`.Email FROM `user` WHERE `user`.username = '".$_POST['userID'][0]."'";
  }
  
 if($c==2){
// $newaction = $newaction .$_POST['userID'][0]." , ". $_POST['userID'][1];
$appquery = "SELECT `user`.Email FROM `user` WHERE `user`.username = '".$_POST['userID'][0]."' || `user`.username = '".$_POST['userID'][1]."'";
}

 if($c==3){
// $newaction = $newaction .$_POST['userID'][0]." , ". $_POST['userID'][1].", ".$_POST['userID'][2];
$appquery = "SELECT `user`.Email FROM `user` WHERE `user`.username = '".$_POST['userID'][0]."' || `user`.username = '".$_POST['userID'][1]."' || `user`.username = '".$_POST['userID'][2]."'";
}
if($c>3){
die("You are not allowed to select more than three reviewers. <a href='javascript:history.back()'>Back</a>");
}

if($appquery){
$Record = mysql_query($appquery, $con) or die(mysql_error());
$row_Record = mysql_fetch_assoc($Record);
$totalRows_Record = mysql_num_rows($Record);
}

//===================================email applicant -- function removed as a result of last meeting
/*
$body = "\r\rThis email message is generated by the IRB online application program. Do not reply.\r\rAn IRB application has been sent to IRB reviewers for review. Should your application be deemed incomplete by IRB, you will receive another email requesting additional information and/or documents. The application number is: ". $_POST['appNum'];

 $to=$_POST['applicant'];
 $subject = "IRB Application ". $_POST['appNum'];
mail($to,$subject,$body);

*/
//++++++++++++++++++++++++++email reviewers
 $subject = "Review IRB Application: ". $_POST['appNum'];
//$headers = "From: ospinfo@txstate.edu";


$body = "\r\rThis email message is generated by the IRB online application program. Do not reply.\r\rYou are assigned to evaluate a new IRB Application. The application number is ".$_POST['appNum'].". If you agree to review this application, Please log in to your IRB account to review the application at:\r".$irbadd.".\r\r If you do not agree to review this application, please inform IRB Chair immediately.";
$body = $body.$emailSig;

do { 

	$to=$row_Record['Email'];
	
/*	$substring = "@txstate.edu"; 

if (strpos($to, $substring) !== false) {
   // Yes, '$substring' is found in '$string';
   mail($to,$subject,$body,$headers);
} 
else {
   echo("The reviewer does not have a Texas State University email address. Click Notice Reviewer to inform him/her that an IRB application has been assigned to him/her. <a href='mailto:".$to."?subject=Review IRB application: ".$appNum."'>Notice Reviewer</a>");
   
   
}
*/
mail($to,$subject,$body,$headers);
	
} while ($row_Record = mysql_fetch_assoc($Record));



 
if ($c==3){
$str="Application Submitted to Reviewers for Review";

  $insertSQL = sprintf("UPDATE application SET irbActionLog=%s, Status = %s, ReviewDate = %s, rev1ID=%s, rev2ID=%s, rev3ID=%s, numReviewers=%s WHERE App_Number=%s", GetSQLValueString($newaction, "text"), GetSQLValueString($str, "text"), GetSQLValueString($today, "text"),GetSQLValueString($_POST['userID'][0], "text"), GetSQLValueString($_POST['userID'][1], "text"), GetSQLValueString($_POST['userID'][2], "text"), $_POST['numReviewers'],GetSQLValueString(trim($_POST['appNum']), "text"));
}


if ($c==2){
$str="Application Submitted to Reviewers for Review";

  $insertSQL = sprintf("UPDATE application SET irbActionLog=%s, Status = %s, ReviewDate = %s, rev1ID=%s, rev2ID=%s, numReviewers=%s WHERE App_Number=%s", GetSQLValueString($newaction, "text"),GetSQLValueString($str, "text"), GetSQLValueString($today, "text"), GetSQLValueString($_POST['userID'][0], "text"), GetSQLValueString($_POST['userID'][1], "text"), $_POST['numReviewers'], GetSQLValueString(trim($_POST['appNum']), "text"));
}
 
 if ($c==1){
$str="Application Submitted to Reviewers for Review";

  $insertSQL = sprintf("UPDATE application SET irbActionLog=%s, Status = %s, ReviewDate = %s, rev1ID=%s, numReviewers=%s WHERE App_Number=%s", GetSQLValueString($newaction, "text"),GetSQLValueString($str, "text"), GetSQLValueString($today, "text"), GetSQLValueString($_POST['userID'][0], "text"), $_POST['numReviewers'], GetSQLValueString(trim($_POST['appNum']), "text"));
}
 
$Result1 = mysql_query($insertSQL, $con) or die(mysql_error());

$insertSQL = "update reviewlog set noticeChair='No', numReviewers = '".$_POST['numReviewers']."', reviewRequestingDate = '".$today."' where appNum='".trim($_POST['appNum'])."'";
$Result2 = mysql_query($insertSQL, $con) or die(mysql_error());

mysql_free_result($Record);

}

//******************************Start of page**********************************************
 
  
  $reviewerAssigned="no";
$query_Recordset = "SELECT irbActionLog, username, Status, trainingFinished, rev1ID, rev2ID, rev3ID FROM application WHERE App_Number = '".$appNum."'";
$Recordset = mysql_query($query_Recordset, $con) or die(mysql_error());
$row_Recordset = mysql_fetch_assoc($Recordset);
$totalRows_Recordset = mysql_num_rows($Recordset);
//if(trim($Recordset['Status']) != "Application Submission Finished")
//die("You are not allowed to assign reviewers for this application. The application may have reviewers assigned or the applicant has not finished submitting the application form.");
 
 //***********************if reviewer assigned, cannot use this page
 
 if ($row_Recordset['rev1ID'] !=""||$row_Recordset['rev2ID']!=""||$row_Recordset['rev3ID']!="")
 {

$reviewerAssigned="yes";
 
 }
 
$query_Recordset1 = "SELECT `user`.username,`user`.FirstName, `user`.LastName,`user`.Department, `user`.User_Type FROM `user` WHERE `user`.User_Type = 'reviewer' order by LastName";
$Recordset1 = mysql_query($query_Recordset1, $con) or die(mysql_error());
$row_Recordset1 = mysql_fetch_assoc($Recordset1);
$totalRows_Recordset1 = mysql_num_rows($Recordset1);
?>



<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
  <meta http-equiv="Content-Type"
 content="text/html; charset=iso-8859-1">
  <title>Texas State University-San Marcos | IRB Online Application</title>
  <LINK href="irbstyle.css" rel="stylesheet" type="text/css">
<script>
function deleteConfirm(a,b,c)
{
if (confirm('Are you sure you want to remove this reviewer from the application? Doing so, the the evaluations/comments that the reviewer ever made to this application will be removed permanently from the record of this application.')){
dirlocation="deleteReviewerAss.php?oldID="+a+"&appNum="+b+"&id="+c;
document.location.href=dirlocation;
}
}
</script>

  <style type="text/css">
<!--
.style43 {font-size: large}
-->
  </style>
</head>
<body>
<table width="800" border="0" align="center" cellpadding="0" cellspacing="0" bgcolor="#FFFFFF" >
  <tr><td>
<table width="800" border="0" align="center" cellpadding="0" cellspacing="0" background="tbbg.gif" >
<tbody>
   <tr background="tbbg.gif">
            <td width="552" valign="top"><p align="left" class="style6 style24"><img src="banner2.jpg" width="550" height="160"></td>
            <td width="248" valign="middle" background="tbbg.gif"><p align="center"> <a class="tsu" href="http://www.txstate.edu">Texas State University</a></p>
              <p align="center"><a class="irbhome" href="index.php" ><span class="style43">I</span>nstitutional <span class="style43">R</span>eview <span class="style43">B</span>oard <span class="style43">O</span>nline <span class="style43">A</span>pplication </p>
           
            </p>
            </span></td>
   </tr>
</tbody></table>
<table width="800" border="0" align="center" bgcolor="#ffffff">
          <tr>
            <td colspan="3" height="19" valign="top" bgcolor="#000000">
			  <div align="center"><span class="style46"><a href='osp_irb_home.php' class="irb">My IRB Home</a> </span><span class="style39">|</span><span class="style46"> <a href="appSummary_irb.php?appNum=<?php echo $appNum;?>" class="irb">Review Application Data</a> </span><span class="style39">|</span><span class="style46"> <a href="statSummary.php?appNum=<?php echo $appNum;?>" class="irb">Summary of Status, Evaluations and Action Logs</a></span><br>
			  <a href="assignReviewer.php?appNum=<?php echo $appNum;?>" class="irb">Assign/Change Reviewer(s)</a> </span><span class="style39">|</span><span class="style46"> <a href="irb_updatestatus.php?appNum=<?php echo $appNum;?>" class="irb"> Update Application Status</a> </span><span class="style39">|</span> <a href="irb_emailApp.php?appNum=<?php echo $appNum;?>" class="irb">Send Comments/Requests to Applicant </a> <span class="style39">|</span> <a href="LogOut.php" class="irb">Log Out</a> </div></td>
          </tr>
  </tbody>
      </table>
      </td>
  </tr><tr>
  <td colspan="3" class="style46"> <div align="center">
    <p>&nbsp;</p>
    <p><strong><span class="style3">ASSIGN REVIEWERS </span><br>
          <br>
      </strong>Application Number:  
    <?php echo $appNum;?></div></td></tr>
  <tr><td colspan="3" align="center"> Human Subject Protection Training: <?php echo strtoupper($row_Recordset['trainingFinished']);?></td></tr>
  <?php
  if (!(strtoupper($row_Recordset['trainingFinished']))=="YES")
die("<tr><td><font color='red'><br>Applicant has not finished Human Subject Protection Training. You cannot submit the application to reviewers.</font></td></tr>");

if($row_Recordset['Status'] == "Approved")
die("<tr><td><font color='red'>The application has been approved. You cannot make any changes on the revieweres of this application.</font></td></tr>");

if($row_Recordset['Status'] == "Discontinued")
die("<tr><td><font color='red'>The application has been approved. You cannot make any changes on the revieweres of this application.</font></td></tr>");

if($row_Recordset['Status'] == "Application Approved - Exempt")
die("<tr><td><font color='red'>The application has been approved. You cannot make any changes on the revieweres of this application.</font></td></tr>");
  if(strtoupper($reviewerAssigned)=="YES"){
  echo "<tr>
  <td colspan='3' class='style47'><br>This application has been assigned reviewer(s), click
</span><a href='addReviewer.php?appNum=".$appNum."'>Add Reviewer(s) </a> link to add more reviewer to this application.<br></td>
</tr>";
}?>

<tr><td><br><table width="500" align="center" bgcolor="#FFFFFF" bordercolordark="#333333" bordercolorlight="#333333" border="0" cellpadding="0" cellspacing="0"><tr><td colspan="3"><div align="center"><?php  if(isset($_POST['insert']) && $_POST['insert'] == "formInsert") echo "<font color='red'>Application reviewer(s) assigned.</font>";?><br><br></td></tr>

<tr><td colspan="3"> <div align="center">
  
  <?php if(strtoupper($reviewerAssigned)=="YES"){
 echo "<p><strong>Reviewer(s) Assigned to this Application</strong></p> <p> </p></div></td></tr>";

if($row_Recordset['rev1ID'])
{
$rev1ID=$row_Recordset['rev1ID'];
$theValue = $rev1ID;
$query_Recordset2 = "SELECT `user`.username,`user`.FirstName, `user`.LastName,`user`.Department, `user`.User_Type FROM `user` WHERE `user`.username = '".$theValue."'";
$Recordset2 = mysql_query($query_Recordset2, $con) or die(mysql_error());
$row_Recordset2 = mysql_fetch_assoc($Recordset2);
$totalRows_Recordset2 = mysql_num_rows($Recordset2);
echo "<tr><td align='center'>".$row_Recordset2['FirstName']." ".$row_Recordset2['LastName'].", ".$row_Recordset2['Department']; 
mysql_free_result($Recordset2);
?>
</td><td><input type='button' value='Change Reviewer' onclick="location.href='changeReviewer.php?oldID=<?php echo $rev1ID;?>&appNum=<?php echo $appNum;?>&id=rev1ID'">

</td>
<td><input type='button' value='Remove Reviewer' onClick="deleteConfirm('<?php echo $rev1ID;?>','<?php echo $appNum;?>','rev1ID')">
 </td></tr>


<?php
}
//********************************
if($row_Recordset['rev2ID'])
{
$rev2ID=$row_Recordset['rev2ID'];
$theValue = $rev2ID;
$query_Recordset2 = "SELECT `user`.username,`user`.FirstName, `user`.LastName,`user`.Department, `user`.User_Type FROM `user` WHERE `user`.username = '".$theValue."'";
$Recordset2 = mysql_query($query_Recordset2, $con) or die(mysql_error());
$row_Recordset2 = mysql_fetch_assoc($Recordset2);
$totalRows_Recordset2 = mysql_num_rows($Recordset2);
echo "<tr><td align='center'>".$row_Recordset2['FirstName']." ".$row_Recordset2['LastName'].", ".$row_Recordset2['Department']; 
mysql_free_result($Recordset2);
?>
</td><td><input type='button' value='Change Reviewer' onclick="location.href='changeReviewer.php?oldID=<?php echo $rev2ID;?>&appNum=<?php echo $appNum;?>&id=rev2ID'">
 
</td>
<td><p>
  <input type='button' value='Remove Reviewer' onClick="deleteConfirm('<?php echo $rev2ID;?>','<?php echo $appNum;?>','rev2ID')">

</p>
  </td></tr>


<?php
}

if($row_Recordset['rev3ID'])
{
$rev3ID=$row_Recordset['rev3ID'];
$theValue = $rev3ID;
$query_Recordset2 = "SELECT `user`.username,`user`.FirstName, `user`.LastName,`user`.Department, `user`.User_Type FROM `user` WHERE `user`.username = '".$theValue."'";
$Recordset2 = mysql_query($query_Recordset2, $con) or die(mysql_error());
$row_Recordset2 = mysql_fetch_assoc($Recordset2);
$totalRows_Recordset2 = mysql_num_rows($Recordset2);
echo "<tr><td align='center'>".$row_Recordset2['FirstName']." ".$row_Recordset2['LastName'].", ".$row_Recordset2['Department']; 
mysql_free_result($Recordset2);
?>
</td><td><input type='button' value='Change Reviewer' onclick="location.href='changeReviewer.php?oldID=<?php echo $rev3ID;?>&appNum=<?php echo $appNum;?>&id=rev3ID'">
</td>
<td><input type='button' value='Remove Reviewer' onClick="deleteConfirm('<?php echo $rev3ID;?>','<?php echo $appNum;?>','rev3ID')"></td></tr>


<?php
}
}//end if assigned reviewers
?></table>

<?php 
if(strtoupper($reviewerAssigned) !="YES"){

?>
<tr>

<td align="center" colspan="3"><span class="style46">
<form action="<?php echo $_SERVER['PHP_SELF'];?>" method="post">
Please indicate how many reviewers you will assign to this application:<br>
2 Reviewers <input name="numReviewers" type="radio" value="2" checked selected/>
<br>
3 Reviewers <input name="numReviewers" type="radio" value="3"/>
<p>To assign reviewer(s) to an IRB application, please select reviewer(s) from the list: </span>
  <p>

<input name="appNum" type="hidden" value="<?php echo $appNum; ?>" />
<input name="Status" type="hidden" value="<?php echo $row_Recordset['Status']; ?>" />
<input name="irbActionLog" type="hidden" value="<?php echo $row_Recordset['irbActionLog']; ?>" />
<input name="reviewerAssigned" type="hidden" value="<?php echo $reviewerAssigned; ?>" />
<input name="applicant" type="hidden" value="<?php echo $row_Recordset['username']; ?>" />
<input name="trainingFinished" type="hidden" value="<?php echo $row_Recordset['trainingFinished']; ?>" />
<select name="userID[]" id="userID[]" multiple size = "10">
<?php 
do {  

        ?>           

  <option value="<?php echo $row_Recordset1['username']; ?>">
  <?php echo $row_Recordset1['LastName']; ?> 
  <?php echo $row_Recordset1['FirstName'].", "; ?>
    
  <?php echo $row_Recordset1['Department']; ?>
  
  <?php $theValue = (!get_magic_quotes_gpc()) ? addslashes($row_Recordset1['username']) : $row_Recordset1['username'];

$query_Recordset3 = "SELECT application.App_Number, rev1Comments, rev2Comments, rev3Comments, application.ProjectTitle, application.Status FROM application WHERE ((application.rev1ID = '".$theValue."' || application.rev2ID = '".$theValue."' || application.rev3ID = '".$theValue."') && (application.Status != 'Approved') && (Status != 'Approved' && Status != 'Applicant Requested Continuation' && Status != 'Application Approved - Exempt'))";
$Recordset3 = mysql_query($query_Recordset3, $con) or die(mysql_error());
$row_Recordset3 = mysql_fetch_assoc($Recordset3);
$totalRows_Recordset3 = mysql_num_rows($Recordset3);
echo " (total assigned: ".$totalRows_Recordset3.", ";
// Revison status
$query_Recordset4 = "SELECT application.Status FROM application WHERE ((application.rev1ID = '".$theValue."' || application.rev2ID = '".$theValue."' || application.rev3ID = '".$theValue."') && (application.Status = 'IRB Chair Requests Revision'))";
$Recordset4 = mysql_query($query_Recordset4, $con) or die(mysql_error());
$row_Recordset4 = mysql_fetch_assoc($Recordset4);
$totalRows_Recordset4 = mysql_num_rows($Recordset4);
//echo $totalRows_Recordset4;

///////////////////// Count reviewed /////////
	$countNoComment =0;
do{


   if(($theValue== $row_Recordset3['rev1ID']) && ($row_Recordset3['rev1Comments']==""))
    
    $countNoComment = $countNoComment + 1;

   elseif(($theValue== $row_Recordset3['rev2ID']) && ($row_Recordset3['rev2Comments']==""))
  
    $countNoComment = $countNoComment + 1;

   elseif(($theValue== $row_Recordset3['rev3ID']) && ($row_Recordset3['rev3Comments']==""))

    $countNoComment = $countNoComment + 1;
	



}while($row_Recordset3=mysql_fetch_assoc($Recordset3));

$countCommented = $totalRows_Recordset3 - $countNoComment;
//echo "commented: ".$countCommented.", not commented: ". $countNoComment.", ";
echo "under revision: ".$totalRows_Recordset4.")";
mysql_free_result($Recordset3);
mysql_free_result($Recordset4);
?>
  </option>
<?php
} while ($row_Recordset1 = mysql_fetch_assoc($Recordset1))
?>
</select><p>

<input name="insert" id="insert" type="hidden" value="formInsert" />
<input name="submit" type="submit" value="Assign Reviewer" />
</form>
<?php

}//end not assigned reviewers

?></td></tr><tr><td>
<table style="width: 100%;" border="0" cellpadding="0" cellspacing="0">
           
                <tr>
                  <td><hr></td>
                </tr>
             
    <tr>
      <td style="vertical-align: top; height: 60px;"><?php include("footer.php"); ?></td>
    </tr>
</table>
</table></td></tr>
</table>
</body>
</html>
<?php
mysql_free_result($Recordset1);
mysql_free_result($Recordset);
//mysql_free_result($Recordset2);
?>
