<?php require_once('Connections/dbc.php');
session_start();
require_once('variables/variables.php');

$restrictGoTo = "unauthorized.php";

function GetSQLValueString($theValue, $theType, $theDefinedValue = "", $theNotDefinedValue = "") 
{
  $theValue = (!get_magic_quotes_gpc()) ? addslashes($theValue) : $theValue;

  switch ($theType) {
    case "text":
      $theValue = ($theValue != "") ? "'" . $theValue . "'" : "NULL";
      break;    
    case "long":
    case "int":
      $theValue = ($theValue != "") ? intval($theValue) : "NULL";
      break;
    case "double":
      $theValue = ($theValue != "") ? "'" . doubleval($theValue) . "'" : "NULL";
      break;
    case "date":
      $theValue = ($theValue != "") ? "'" . $theValue . "'" : "NULL";
      break;
    case "defined":
      $theValue = ($theValue != "") ? $theDefinedValue : $theNotDefinedValue;
      break;
  }
  return $theValue;
}



if (!isset($_SESSION['username'])){   
 
  header("Location: ". $restrictGoTo); 
  exit;
}


if (!($_SESSION['User_Type'] == "IRB Staff")) {   
 
  //header("Location: ". $restrictGoTo); 
 // exit;
//}

if (!($_SESSION['User_Type'] == "IRB Chair")) {   
 
  header("Location: ". $restrictGoTo); 
  exit;
}
}

 
//catch info from assign reviewer page

 $appNum = $_GET['appNum'];

$rev=$_GET['id'];
$oldID=$_GET['oldID'];

$query_Recordset = "SELECT irbActionLog, Status, username FROM application WHERE App_Number = '".$appNum."'";
$Recordset = mysql_query($query_Recordset, $con) or die(mysql_error());
$row_Recordset = mysql_fetch_assoc($Recordset);
$totalRows_Recordset = mysql_num_rows($Recordset);
if(trim($row_Recordset) == "Approved")
die("The application has been approved. You cannot make any changes on the revieweres.");
 
$query_Recordset1 = "SELECT `user`.username,`user`.FirstName, `user`.LastName,`user`.Department, `user`.User_Type, `user`.Email FROM `user` WHERE `user`.User_Type = 'reviewer'";
$Recordset1 = mysql_query($query_Recordset1, $con) or die(mysql_error());
$row_Recordset1 = mysql_fetch_assoc($Recordset1);
$totalRows_Recordset1 = mysql_num_rows($Recordset1);

//**************************submit info from self*********************


  if(isset($_POST['insertSelf']) && $_POST['insertSelf'] == "formInsert")
 {
  $appNum = $_POST['appNum'];
$today=date("m/d/y H:i:s");
  $newaction=$_POST['irbActionLog']."<br>".$today."  ".$_SESSION['username'].":<br>";
  $strID=explode(",", $_POST['userID']);

  $revID=$strID[0];
  $revEmail=$strID[1];
 $revChange = trim($_POST['oldID']);
 
 $theValue = (!get_magic_quotes_gpc()) ? addslashes($revChange) : $revChange;
 $query_oldemail = "SELECT `user`.Email FROM `user` WHERE `user`.username = '".$theValue."'";
$emailRecordset = mysql_query($query_oldemail, $con) or die(mysql_error());
$row_emailRecordset = mysql_fetch_assoc($emailRecordset);
$totalRows_emailRecordset = mysql_num_rows($emailRecordset);
 
 
 $rev=trim($_POST['rev']);
 $newaction = $newaction."Replace reviewer <em>".$revChange."</em> with <em>".$revID."</em><br>";
 //echo "Reviewer has been changed from <em>".$revChange."</em> to <em> ".$revID.".<br>";
 if ($rev=='rev1ID'){
  $insertSQL = sprintf("UPDATE application SET irbActionLog=%s, rev1ID=%s, rev1Comments=%s, rev1Approved = %s WHERE App_Number=%s", GetSQLValueString($newaction, "text"), GetSQLValueString($revID, "text"), GetSQLValueString("","text"), GetSQLValueString("","text"), GetSQLValueString($_POST['appNum'], "text"));
 }
 
  if ($rev=='rev2ID'){
  $insertSQL = sprintf("UPDATE application SET irbActionLog=%s, rev2ID=%s, rev2Comments=%s, rev2Approved = %s WHERE App_Number=%s", GetSQLValueString($newaction, "text"), GetSQLValueString($revID, "text"),GetSQLValueString("","text"), GetSQLValueString("","text"), GetSQLValueString($_POST['appNum'], "text"));
 }
  if ($rev=='rev3ID'){
  $insertSQL = sprintf("UPDATE application SET irbActionLog=%s, rev3ID=%s, rev3Comments=%s, rev3Approved = %s WHERE App_Number=%s", GetSQLValueString($newaction, "text"), GetSQLValueString($revID, "text"), GetSQLValueString("","text"), GetSQLValueString("","text"), GetSQLValueString($_POST['appNum'], "text"));
 }
 
 $Result1 = mysql_query($insertSQL, $con) or die(mysql_error());
 
 //email notification to the old reviewer
 $to=$row_emailRecordset['Email'];
 $oEmail=$row_emailRecordset['Email'];
   $subject = "IRB Application Reviewer Change: ". $_POST['appNum'];
 
$body = "\r\rThis email message is generated by the IRB online application program. Do not reply.\r\rYou do not need to review the IRB Application that was assigned to you previously. The application number is ".$_POST['appNum'].". If you have any questions, please contact IRB Chairs.";
$body = $body.$emailSig;
$substring = "@txstate.edu"; 

if (strpos($to, $substring) !== false) {
   // Yes, '$substring' is found in '$string';
   mail($to,$subject,$body,$headers);
  
} 

 mysql_free_result($emailRecordset);
 //email notification to the new reviewer
  $subject = "You are assigned to review IRB application: ". $_POST['appNum'];
 //$headers = "From: ospinfo@txstate.edu";
$body = "\r\rThis email message is generated by the IRB online application program. Do not reply.\r\rYou are assigned to evaluate a new IRB Application. The application number is ".$_POST['appNum'].". If you agree to review this application,  Please log into your IRB account to review the application at:\r".$irbadd.".\r\r If you do not agree to review this application, please inform IRB chairs immediately.";

$body = $body.$emailSig;

	$to=$revEmail;
	$substring = "@txstate.edu"; 

if (strpos($to, $substring) !== false) {
   // Yes, '$substring' is found in '$string';
   mail($to,$subject,$body,$headers);
   
} 
if ((strpos($revEmail, $substring) !== false)&&(strpos($oEmail, $substring) !== false)){
header("Location: assignReviewer.php?appNum=".$appNum); 
 	exit;

	}
	

 }

?>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
  <meta http-equiv="Content-Type"
 content="text/html; charset=iso-8859-1">
  <title>Texas State University-San Marcos | IRB Online Application</title>
  <LINK href="irbstyle.css" rel="stylesheet" type="text/css">


  <style type="text/css">
<!--
.style43 {font-size: large}
-->
  </style>
</head>
<body>
<table width="800" border="0" align="center" cellpadding="0" cellspacing="0" bgcolor="#FFFFFF" >
  <tr><td>
<table width="800" border="0" align="center" cellpadding="0" cellspacing="0" background="tbbg.gif" >
<tbody>
   <tr background="tbbg.gif">
            <td width="552" valign="top"><p align="left" class="style6 style24"><img src="banner2.jpg" width="550" height="160"></td>
            <td width="248" valign="middle" background="tbbg.gif"><p align="center"> <a class="tsu" href="http://www.txstate.edu">Texas State University</a></p>
              <p align="center"><a class="irbhome" href="index.php" ><span class="style43">I</span>nstitutional <span class="style43">R</span>eview <span class="style43">B</span>oard <span class="style43">O</span>nline <span class="style43">A</span>pplication </p>
           
            </p>
            </span></td>
   </tr>
</tbody></table>
<table width="800" border="0" align="center" bgcolor="#ffffff">
          <tr>
            <td colspan="3" height="19" valign="top" bgcolor="#000000">
			  <div align="center"><span class="style46"><a href='osp_irb_home.php' class="irb">My IRB Home</a> </span><span class="style39">|</span><span class="style46"> <a href="appSummary_irb.php?appNum=<?php echo $appNum;?>" class="irb">Review Application Data</a> </span><span class="style39">|</span><span class="style46"> <a href="statSummary.php?appNum=<?php echo $appNum;?>" class="irb">Summary of Status, Evaluations and Action Logs</a></span><br>
			  <a href="assignReviewer.php?appNum=<?php echo $appNum;?>" class="irb">Assign/Change Reviewer(s)</a> </span><span class="style39">|</span><span class="style46"> <a href="irb_updatestatus.php?appNum=<?php echo $appNum;?>" class="irb"> Update Application Status</a> </span><span class="style39">|</span> <a href="irb_emailApp.php?appNum=<?php echo $appNum;?>" class="irb">Send Comments/Requests to Applicant </a> <span class="style39">|</span> <a href="LogOut.php" class="irb">Log Out</a> </div></td>
          </tr>
  </tbody>
      </table>
      </td>
  </tr>

<tr><td><?php  if(isset($_POST['insertSelf']) && $_POST['insertSelf'] == "formInsert") 
{
echo "Application reviewer changed. ";
  $strID=explode(",", $_POST['userID']);

  $revID=$strID[0];
  $revEmail=$strID[1];
 echo "<em>".$_POST['oldID']."</em> was replace by <em> ".$revID."</em><br>";
 
  $revChange = trim($_POST['oldID']);
 
 $theValue = (!get_magic_quotes_gpc()) ? addslashes($revChange) : $revChange;
 $query_oldemail = "SELECT `user`.Email FROM `user` WHERE `user`.username = '".$theValue."'";
$emailRecordset = mysql_query($query_oldemail, $con) or die(mysql_error());
$row_emailRecordset = mysql_fetch_assoc($emailRecordset);
$totalRows_emailRecordset = mysql_num_rows($emailRecordset);
$oldEmail=$row_emailRecordset['Email'];

$substring = "@txstate.edu"; 

if (strpos($oldEmail, $substring) == false) {
   // '$substring' is not found in '$string';

   echo("<p><b>Important! The reviewer ".$revChange." does not have a Texas State University email address. Click Notice Reviewer to inform him/her that an IRB application has been assigned to him/her.</b> <a href='mailto:".$oldEmail."?subject=Review IRB application: ".$appNum."&body=You do not need to review the IRB Application that was assigned to you previously. The application number is ".$_POST['appNum']."'>Notice Reviewer</a><br>");
mysql_free_result($emailRecordset);
}

if (strpos($revEmail, $substring) == false) {
   // '$substring' is not found in '$string';

   echo("<p><b>Important! The reviewer ".$revID." does not have a Texas State University email address. Click Notice Reviewer to inform him/her that an IRB application has been assigned to him/her.</b> <a href='mailto:".$revEmail."?subject=Review IRB application: ".$appNum."&body=You are assigned to evaluate a new IRB Application. The application number is ".$_POST['appNum'].". If you agree to review this application,  please log into your IRB account to review the application at:\r".$irbadd.".\r\r If you do not agree to review this application, please inform IRB chairs immediately.'>Notice Reviewer</a><br>");

}
 }
?></td></tr>

<tr>
<?php
if(!($_POST['insertSelf'] == "formInsert")){
?>
<td align="center"><span class="style46"><br><br>
    <strong>Select a Reviewer from the List</strong> </span>
  <p>
<form action="<?php echo $_SERVER['PHP_SELF'];?>" method="post"  >
<input name="appNum" type="hidden" value="<?php echo $appNum; ?>" />
<input name="irbActionLog" type="hidden" value="<?php echo $row_Recordset['irbActionLog']; ?>" />
<input name="applicant" type="hidden" value="<?php echo $row_Recordset['username']; ?>" />
<input name="rev" type="hidden" value="<?php echo $rev; ?>" />
<input name="oldID" type="hidden" value="<?php echo $oldID; ?>" />
<select name="userID" id="userID" size="10">
<?php 
do {  

        ?>           

  <option value="<?php echo $row_Recordset1['username'].",".$row_Recordset1['Email']; ?>">
  <?php echo $row_Recordset1['LastName']; ?> 
  <?php echo $row_Recordset1['FirstName'].", "; ?>
    
  <?php echo $row_Recordset1['Department']; ?>
   <?php $theValue = (!get_magic_quotes_gpc()) ? addslashes($row_Recordset1['username']) : $row_Recordset1['username'];

$query_Recordset3 = "SELECT application.App_Number, rev1Comments, rev2Comments, rev3Comments, application.ProjectTitle FROM application WHERE ((application.rev1ID = '".$theValue."' || application.rev2ID = '".$theValue."' || application.rev3ID = '".$theValue."') && (application.Status != 'Approved'))";
$Recordset3 = mysql_query($query_Recordset3, $con) or die(mysql_error());
$row_Recordset3 = mysql_fetch_assoc($Recordset3);
$totalRows_Recordset3 = mysql_num_rows($Recordset3);
echo " (total assigned: ".$totalRows_Recordset3.", ";

// Revison status
$query_Recordset4 = "SELECT application.Status FROM application WHERE ((application.rev1ID = '".$theValue."' || application.rev2ID = '".$theValue."' || application.rev3ID = '".$theValue."') && (application.Status = 'IRB Chair Requests Revision'))";
$Recordset4 = mysql_query($query_Recordset4, $con) or die(mysql_error());
$row_Recordset4 = mysql_fetch_assoc($Recordset4);
$totalRows_Recordset4 = mysql_num_rows($Recordset4);
//echo $totalRows_Recordset4;

///////////////////// Count reviewed /////////
	$countNoComment =0;
do{


   if(($theValue== $row_Recordset3['rev1ID']) && ($row_Recordset3['rev1Comments']==""))
    
    $countNoComment = $countNoComment + 1;

   elseif(($theValue== $row_Recordset3['rev2ID']) && ($row_Recordset3['rev2Comments']==""))
  
    $countNoComment = $countNoComment + 1;

   elseif(($theValue== $row_Recordset3['rev3ID']) && ($row_Recordset3['rev3Comments']==""))

    $countNoComment = $countNoComment + 1;
	
}while($row_Record3=mysql_fetch_assoc($Recordset3));
$countCommented = $totalRows_Recordset3 - $countNoComment;
//echo "commented: ".$countCommented.", not commented: ". $countNoComment.", ";
echo "under revision: ".$totalRows_Recordset4.")";
mysql_free_result($Recordset3);
mysql_free_result($Recordset4);

?>
  </option>
<?php
} while ($row_Recordset1 = mysql_fetch_assoc($Recordset1))
?>
</select><p>
<input name="submit" type="submit" value="Update Reviewer" />
<input name="insertSelf" id="insertSelf" type="hidden" value="formInsert" />
</form>
</td></tr>
<?php
}
?>
<tr><td>
<table style="width: 100%;" border="0" cellpadding="0" cellspacing="0">
           
                <tr>
                  <td><hr></td>
                </tr>
             
    <tr>
      <td style="vertical-align: top; height: 60px;"><?php include("footer.php"); ?></td>
    </tr>
</table>

</table>
</body>
</html>
<?php
mysql_free_result($Recordset1);
//mysql_free_result($Recordset);
//mysql_free_result($Recordset2);
?>
