<?php require_once('Connections/con3.php');
session_start();

$restrictGoTo = "unauthorized.php";

if (!isset($_SESSION['username'])){   
 
  header("Location: ". $restrictGoTo); 
  exit;
}

if (!($_SESSION['User_Type'] == "reviewer")) {   
 
  header("Location: ". $restrictGoTo); 
  exit;
}

function GetSQLValueString($theValue, $theType, $theDefinedValue = "", $theNotDefinedValue = "") 
{
  $theValue = (!get_magic_quotes_gpc()) ? addslashes($theValue) : $theValue;

  switch ($theType) {
    case "text":
      $theValue = ($theValue != "") ? "'" . $theValue . "'" : "NULL";
      break;    
    case "long":
    case "int":
      $theValue = ($theValue != "") ? intval($theValue) : "NULL";
      break;
    case "double":
      $theValue = ($theValue != "") ? "'" . doubleval($theValue) . "'" : "NULL";
      break;
    case "date":
      $theValue = ($theValue != "") ? "'" . $theValue . "'" : "NULL";
      break;
    case "defined":
      $theValue = ($theValue != "") ? $theDefinedValue : $theNotDefinedValue;
      break;
  }
  return $theValue;
}

$time=date("m/d/y H:i:s");


$editFormAction = $_SERVER['PHP_SELF'];
if (isset($_SERVER['QUERY_STRING'])) {
  $editFormAction .= "?" . htmlentities($_SERVER['QUERY_STRING']);
}

	
	//**************************************************************
	
	
if ((isset($_POST["MM_update"])) && ($_POST["MM_update"] == "form")) {
$today=date("m/d/y H:i:s");
mysql_select_db($database_con3, $con3);
$query_Recordset0 = "SELECT irbActionLog FROM `application` where App_Number='".$_POST['appNum']."'";
$Recordset0 = mysql_query($query_Recordset0, $con3) or die(mysql_error());
$row_Recordset0 = mysql_fetch_assoc($Recordset0);
$totalRows_Recordset0 = mysql_num_rows($Recordset0);

	$appNum=$_POST['appNum'];
	 $newaction=$row_Recordset0['irbActionLog']."<br><br>".$today."  ".$_SESSION['name'].":<br>";
	 $newaction = $newaction."Reviewer Declined the Evaluation of the Application.";
	
	
	if ($_POST['appNum'] !=""){
  $updateSQL = sprintf("UPDATE application SET irbActionLog=%s WHERE App_Number=%s",GetSQLValueString($newaction, "text"), GetSQLValueString($_POST['appNum'], "text"));

  mysql_select_db($database_con3, $con3);
  $Result1 = mysql_query($updateSQL, $con3) or die(mysql_error());
  
  //***********************************************************
mysql_select_db($database_con3, $con3);
$query_Recordset = "SELECT FirstName, LastName, Email FROM `user` where username='".$_SESSION['username']."'";
$Recordset = mysql_query($query_Recordset, $con3) or die(mysql_error());
$row_Recordset = mysql_fetch_assoc($Recordset);
$totalRows_Recordset = mysql_num_rows($Recordset);

//*********************************************************
mysql_select_db($database_con3, $con3);
$query_Recordset1 = "SELECT Email FROM `user` where User_Type='IRB Chair'";
$Recordset1 = mysql_query($query_Recordset1, $con3) or die(mysql_error());
$row_Recordset1 = mysql_fetch_assoc($Recordset1);
$totalRows_Recordset = mysql_num_rows($Recordset1);
  $from="From: ".$_SESSION['Email'];
	
	$body = "\r\rThis email message is generated by the IRB online application program. Do not reply.\r\rReviewer ".$row_Recordset['FirstName']." ".$row_Recordset['LastName']." has just declined the assignment of reviewing IRB application ".$_POST['appNum']. ".\r\rExplanations:\r".$_POST['msg'];
    
	$subject = "Reviewer ".$_SESSION['name']." declined IRB assignment: ".$_POST['appNum'];

//********************************************************************************


do
{


  $to = $row_Recordset1['Email'];
	mail($to,$subject,$body, $from);


}while($row_Recordset1 = mysql_fetch_assoc($Recordset1));
header("Location: rev_Home.php"); 
 exit;
  
 mysql_free_result($Recordset0);
  mysql_free_result($Recordset);
   mysql_free_result($Recordset1);
}//if appnum
}//if post form
$appNum=$_GET['appNum'];

?>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
  <meta http-equiv="Content-Type"
 content="text/html; charset=iso-8859-1">
  <title>Texas State University-San Marcos | IRB Online Application</title>
  <LINK href="irbstyle.css" rel="stylesheet" type="text/css">


  <style type="text/css">
<!--
.style42 {color: #FFFFFF}
.style43 {font-size: large}
-->
  </style>
</head>
<body>
<table width="800" border="0" align="center" cellpadding="0" cellspacing="0" bgcolor="#FFFFFF" >
  <tr><td>
<table width="800" border="0" align="center" cellpadding="0" cellspacing="0" background="tbbg.gif" >
<tbody>
   <tr background="tbbg.gif">
            <td width="552" valign="top"><p align="left" class="style6 style24"><img src="banner2.jpg" width="550" height="160"></td>
            <td width="248" valign="middle" background="tbbg.gif"><p align="center"> <a class="tsu" href="http://www.txstate.edu">Texas State University</a></p>
              <p align="center"><a class="irbhome" href="index.php" ><span class="style43">I</span>nstitutional <span class="style43">R</span>eview <span class="style43">B</span>oard <span class="style43">O</span>nline <span class="style43">A</span>pplication </p>
           </a>
            </p>
            </span></td>
   </tr>
          
       
        </tbody>
      </table>
      </td>
  </tr>
</tbody></table>
<table width="800" border="0" align="center" bgcolor="#ffffff">
  <tr>
    <td colspan="4" bgcolor="#000000"><div align="center">
			  <div align="center"><span class="style46">
			  <div align="center" class="style6"><span class="style2"><a href="<?php echo $_SESSION['myhome'];?>" class="irb">My IRB Home</a> </span><span class="style42">| </span><span class="style2"><a href="reviewer_app.php" class="irb">Evaluate Applications Assigned </a> </span><span class="style42">| </span><span class="style2"><a href="rev_listApp.php" class="irb">List All IRB Applications</a> <span class="style42">|</span> <a href="LogOut.php" class="irb">Log Out</a></span></div></td>
          </tr>
  
    <tr bgcolor="#FFFFFF">
      <td height="348" valign="top" bgcolor="#FFFFFF"><div align="center">
          <p>&nbsp;</p>
        <p align="center"><?php echo $_SESSION['name'];?></p>
     
        <p><strong>DECLINE IRB APPLICATION EVALUATION ASSIGNMENT </strong></p>
        <p class="style32"> If you come to this page by mistake, please click the &quot;Back&quot; button on your brower window. </p>
      </div>
	 
        <table width="800" bgcolor="#FFFFFF"> 
          <tr><td width="700" >
	   
	    <form name="form" action="<?php echo $editFormAction; ?>" method="POST">
		  <div align="center">
		    <p align="left">Please Enter Your Explanations Here:
		            </p>
		    <p>
		      <textarea name="msg" cols="80" rows="8"></textarea>
		      
		      
	          <br>
	          <input type="hidden" name="appNum" value="<?php echo $appNum; ?>">
	          <input type="hidden" name="MM_update" value="form">
	          <input name="submit" type="submit" value="Send Message and Return Home">
            </p>
	      </div>
	    </form>

	  </td></tr></table></td></tr><tr><td><table style="width: 100%;" border="0" cellpadding="0" cellspacing="0">
           
                <tr>
                  <td><hr></td>
                </tr>
             
    <tr>
      <td style="vertical-align: top; height: 60px;"><?php include("footer.php"); ?></td>
    </tr>
</table>
	   </table></td></tr>
	  
	  </td></tr></table>
</body>
</html>

