<?php require_once('Connections/con3.php');
session_start();

$restrictGoTo = "unauthorized.php";

if (!isset($_SESSION['username'])){   
 
  header("Location: ". $restrictGoTo); 
  exit;
}



function GetSQLValueString($theValue, $theType, $theDefinedValue = "", $theNotDefinedValue = "") 
{
  $theValue = (!get_magic_quotes_gpc()) ? addslashes($theValue) : $theValue;

  switch ($theType) {
    case "text":
      $theValue = ($theValue != "") ? "'" . $theValue . "'" : "NULL";
      break;    
    case "long":
    case "int":
      $theValue = ($theValue != "") ? intval($theValue) : "NULL";
      break;
    case "double":
      $theValue = ($theValue != "") ? "'" . doubleval($theValue) . "'" : "NULL";
      break;
    case "date":
      $theValue = ($theValue != "") ? "'" . $theValue . "'" : "NULL";
      break;
    case "defined":
      $theValue = ($theValue != "") ? $theDefinedValue : $theNotDefinedValue;
      break;
  }
  return $theValue;
}

$time = date("m-d-y");


$editFormAction = $_SERVER['PHP_SELF'];
if (isset($_SERVER['QUERY_STRING'])) {
  $editFormAction .= "?" . htmlentities($_SERVER['QUERY_STRING']);
}

if ((isset($_POST["MM_update"])) && ($_POST["MM_update"] == "form")) {
	$appNum=$_POST['appNum'];
	
	//**************************************************************
	$today = date("m-d-y");
	 $newaction=$_POST['irbActionLog']."<br>".$today."  ".$_SESSION['username'].":<br>";
	 $newaction = $newaction." Email comments/request to applicant.";
	
	$msg=$_POST['prev_msg']."<br><br>".$_POST['msg'];
  $updateSQL = sprintf("UPDATE application SET irbActionLog=%s WHERE App_Number=%s",GetSQLValueString($newaction, "text"), GetSQLValueString($_POST['appNum'], "text"));

  mysql_select_db($database_con3, $con3);
  $Result1 = mysql_query($updateSQL, $con3) or die(mysql_error());
  
  
  
	$to = $_POST['appEmail'];
//	$from = "From: ospinfo@txstate.edu";
	$body = "\r\rThis email message is generated by the IRB online application program. Do not reply.\r\rApplication Number: ".$_POST['appNum']."\r\r".$_POST['msg'];
    
	$subject = $_POST['subject'];

	mail($to,$subject,$body);
 // $to = $_SESSION['Email'];
	//mail($to,$subject,$body);
	

 
}

//********************************************************************************
mysql_select_db($database_con3, $con3);
$query_Recordset1 = "SELECT irbActionLog,application.rev1Comments, application.rev2Comments, application.rev1Approved, application.rev2Approved, application.rev1ApprovedDate, application.rev2ApprovedDate, application.rev1ID, application.rev2ID, application.irbEmails, application.rev3ID, application.rev3Approved, application.rev3ApprovedDate, application.rev3Comments, application.App_Number, application.username FROM application where App_Number='".$appNum."'";
$Recordset1 = mysql_query($query_Recordset1, $con3) or die(mysql_error());
$row_Recordset1 = mysql_fetch_assoc($Recordset1);
$totalRows_Recordset1 = mysql_num_rows($Recordset1);

mysql_select_db($database_con3, $con3);
$query_Recordset2 = "SELECT `user`.Email, `user`.username FROM `user` where username='".$row_Recordset1['username']."'";
$Recordset2 = mysql_query($query_Recordset2, $con3) or die(mysql_error());
$row_Recordset2 = mysql_fetch_assoc($Recordset2);
$totalRows_Recordset2 = mysql_num_rows($Recordset2);


?>



<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
  <meta http-equiv="Content-Type"
 content="text/html; charset=iso-8859-1">
  <title>Texas State University-San Marcos </title>
  <style type="text/css">
<!--
.style4 {
	font-family: Georgia, "Times New Roman", Times, serif;
	font-size: 40px;
	color: #333399;
}
.style6 {
	font-family: Arial, Helvetica, sans-serif;
	color: #333399;
	font-weight: bold;
}
.style7 {
	font-family: Arial, Helvetica, sans-serif;
	font-size: 12px;
	color: #4d3319;
}
a.navbar:link {
	color: #4d3319;
	font-family: Arial, Helvetica, sans-serif;
	font-size: 10px;
	font-weight: normal;
}
a.navbar:visited {
	color: #4d3319;
	text-decoration: none;
	font-family: Arial, Helvetica, sans-serif;
	font-size: 10px;
}
a.navbar:hover {
	font-family: Arial, Helvetica, sans-serif;
	font-size: 10px;
	text-decoration: underline;
}
a.body:link {
	font-family: Arial, Helvetica, sans-serif;
	font-size: 12px;
	color: #336699;
	text-decoration: underline;
}
a.body:visited {
	font-family: Arial, Helvetica, sans-serif;
	color: #4D3319;
	text-decoration: underline;
}

a.irb:link{
font-family: Arial, Helvetica, sans-serif;
	color: #336699;
	text-decoration: none;

}
a.irb:visited {
	font-family: Arial, Helvetica, sans-serif;
	color: #336699;
	text-decoration: none;
}
-->
  </style>
  <style type="text/css">
<!--
.style14 {font-size: small}
body {
	background-color: #cccccc;
}
.style16 {
	color: #FFFFFF;
	font-weight: bold;
}
.style21 {font-size: 12px}
.style44 {font-family: Verdana, Arial, Helvetica, sans-serif}
.style46 {font-family: Verdana, Arial, Helvetica, sans-serif; font-size: small; }
-->
  </style>
</head>
<body><table width="800" border="1" align="center" cellpadding="5" cellspacing="0" bgcolor="#FFFFFF" >
  <tr><td>
<table width="800" border="0" align="center" cellpadding="5" cellspacing="0" >
<tbody>
   <tr>
            <td valign="top" bgcolor="#330000"><a
 href="http://www.txstate.edu"><img src="txstate_logo2.gif"
 alt="TxState" name="TxState" id="TxState" border="0"></a></td>
            <td width="99" valign="top" bgcolor="#330000" class="style4"><br>            </td>
            <td bgcolor="#330000">
              <div class="style7" align="right"><a href="LogOut.php" class="style14 style16">Log
Out</a></div></td>
          </tr>
          
        <tr>
            <td colspan="3" height="21" valign="top">
            <div align="center">
              <p>&nbsp;</p>
              <p><a class="irb" href="index.php"><span class="style21"><strong>Institutional Review Board</strong></span></a>              </p>
              <p class="style6">Online Application
              <hr>
            </div></td>
          </tr>
          <tr>
            <td colspan="3" height="19" valign="top">
			  <div align="center"><span class="style46"><a href='osp_irb_home.php'>OSP IRB Home</a> | <a href="assignReviewer.php?appNum=<?php echo $appNum;?>">Assign Reviewer(s)</a> | <a href="irb_updatestatus.php?appNum=<?php echo $appNum;?>"> Update Application Status</a> |</span><span class="style44"> <a href="irb_emailApp.php?appNum=<?php echo $appNum;?>" class="style46">Email Applicant Comments/Request </a></span></div></td>
          </tr>
  </tbody>
      </table>
      </td>
  </tr>
    <tr>
      <td height="348" valign="top"><div align="center"><strong>Application Number: <?php echo $appNum;?> 
      </strong></div>
        <table border="1" cellpadding="0" cellspacing="0" width="97%">
	  
	  <tr><td valign="top"><p>Reviewer 1:<br>
	    Approved? <?php echo $row_Recordset1['rev1Approved']; ?>
		<?php if ($row_Recordset1['rev1Approved'] == "yes" ||$row_Recordset1['rev1Approved'] == "Yes")
	    echo "Date of Approval: ". $row_Recordset1['rev1ApprovedDate']; ?><br>
	        <br>
	        <strong>Comments:</strong><br>
	        <?php echo $row_Recordset1['rev1Comments']; ?></p>
	      </td>
	  <td valign="top">Reviewer 2:<br>
	  Approved? 
	  <?php echo $row_Recordset1['rev2Approved']; ?>
	  <br>
	  <?php if ($row_Recordset1['rev2Approved'] == "yes" ||$row_Recordset1['rev2Approved'] == "Yes")
	  echo "Date of Approval: ". $row_Recordset1['rev2ApprovedDate']; ?><br>
	  <br>
	  <strong>Comments:	  </strong><br>
	  <?php echo $row_Recordset1['rev2Comments']; ?></td>
	   
	 <?php if ($row_Recordset1['rev3ID']){?>
	  <td valign="top"> Reviewer 3:<br>
	  Approved? <?php echo $row_Recordset1['rev3Approved']; ?>
	  <br>
	  <?php if ($row_Recordset1['rev3Approved'] == "yes" ||$row_Recordset1['rev3Approved'] == "Yes")
	  echo "Date of Approval: ".$row_Recordset1['rev3ApprovedDate']; ?><br>
	  Comments:
	  <br>
	  <?php echo $row_Recordset1['rev3Comments']."</td>"; 
	  }?>	  </tr></table>
	  
	  
	  
	  <table><tr><td >
	    <p>&nbsp;</p>
	    <p><strong>Email Message to the Applicant:</strong><br>
	       
	    </p>
	    <form name="form1" action="<?php echo $editFormAction; ?>" method="POST">
	  <?php if($row_Recordset1['irbEmails'] !=""){?>
	  Message Sent:<br>
	  <input name="prev_msg" type="hidden" id="prev_msg" value="<?php echo $row_Recordset1['irbEmails']; ?>">
	    <?php echo $row_Recordset1['irbEmails']; ?>
	  <?php } ?>
	   <p><br><label>Subject:
	        <input type="text" name="subject">
	        </label>
	 <br> New Message:<br>
	  <textarea name="msg" cols="80" rows="8"><?php echo $time.":\r";?></textarea>
	  <input type="hidden" name="irbActionLog" ID="irbActionLog" value="<?php echo $row_Recordset1['irbActionLog'];?>">
	   <input type="hidden" name="appNum" ID="appNum" value="<?php echo $appNum;?>">
	 <br> <input name="submit" type="submit" value="Send Message">
	  <input type="hidden" name="appEmail" value="<?php echo $row_Recordset2['Email']; ?>">
	  <input type="hidden" name="MM_update" value="form1">
	  <input type="hidden" name="appNum" value="<?php echo $appNum;?>">
	  </form>
	  
	  
	  </td></tr></table></td>
    </tr></table>
	
	  
</body>
</html>
<?php
mysql_free_result($Recordset1);

mysql_free_result($Recordset2);
?>
