<?php require_once('Connections/con3.php'); 
require_once('Connections/dbc.php');
session_start();

?>
 <?php

$restrictGoTo = "unauthorized.php";

if (!isset($_SESSION['username'])){   
 
  header("Location: ". $restrictGoTo); 
  exit;
}


if (!($_SESSION['User_Type'] == "IRB Staff")) {
	if (!($_SESSION['User_Type'] == "IRB Chair")) {
   
 
  header("Location: ". $restrictGoTo); 
  exit;
  }
}




 

//echo "<p>Application Numer: ".$appNumber."</p>";


$appNum = $_GET['appNum'];
mysql_select_db($database_con3, $con3);
$query_Recordset1 = "SELECT irbActionLog, application.ProjectTitle, application.username, application.ProjectTitle, Status, ReceivedDate, ReviewDate, RevisionRequestDate, RevisionDate, ApprovedDate, trainingFinished, irbActionLog FROM application where App_Number='".$appNum."'";
$Recordset1 = mysql_query($query_Recordset1, $con3) or die(mysql_error());
$row_Recordset1 = mysql_fetch_assoc($Recordset1);
$totalRows_Recordset1 = mysql_num_rows($Recordset1);
$applicant=$row_Recordset1['username'];

mysql_select_db($database_con3, $con3);
$query_Recordset2 = "SELECT `user`.Email FROM `user` where username='".$applicant."'";
$Recordset2 = mysql_query($query_Recordset2, $con3) or die(mysql_error());
$row_Recordset2 = mysql_fetch_assoc($Recordset2);
$totalRows_Recordset2 = mysql_num_rows($Recordset2);
$emailAdd=$row_Recordset2['Email'];


 function GetSQLValueString($theValue, $theType, $theDefinedValue = "", $theNotDefinedValue = "") 
{
  $theValue = (!get_magic_quotes_gpc()) ? addslashes($theValue) : $theValue;

  switch ($theType) {
    case "text":
      $theValue = ($theValue != "") ? "'" . $theValue . "'" : "NULL";
      break;    
    case "long":
    case "int":
      $theValue = ($theValue != "") ? intval($theValue) : "NULL";
      break;
    case "double":
      $theValue = ($theValue != "") ? "'" . doubleval($theValue) . "'" : "NULL";
      break;
    case "date":
      $theValue = ($theValue != "") ? "'" . $theValue . "'" : "NULL";
      break;
    case "defined":
      $theValue = ($theValue != "") ? $theDefinedValue : $theNotDefinedValue;
      break;
  }
  return $theValue;
}

if(isset($_POST['insert']) && $_POST['insert'] == "formInsert")
 {
 $appNum = $_POST['appNum'];
  $today = date("m-d-y");
  $newaction=$_POST['irbActionLog']."<br>".$today."  ".$_SESSION['username'].":<br>";
  $subject="";
  
  //******************************************************
  if($_POST['newstatus'] == "Application in Process") {
$newaction=$newaction."IRB administrator/chair changed the application status into Application in Process.";
 $subject = "IRB Application ". $_POST['appNum'].": IRB administrator/chair changed the application status into Application in Process";
  $insertSQL = sprintf("UPDATE application SET irbActionLog=%s, Status=%s WHERE App_Number=%s", GetSQLValueString($newaction, "text"), GetSQLValueString($_POST['newstatus'], "text"), GetSQLValueString($_POST['appNum'], "text"));
 $body = "\r\rThis email message is generated by the IRB online application program. Do not reply.\r\rIRB administrator/chair changed the application status into Application in Process. Applicant can make revisions to the application. The application number is: ". $_POST['appNum'];
    
 	}
  //************************************************************
	if($_POST['newstatus'] == "Application Received. Submitted for Varification of Human Subject Protection Training") {
$newaction=$newaction."IRB Online Application informed the applicant that the application was received and was submitted for varification of Human Subject Protection Training";
 $subject = "IRB Application ". $_POST['appNum'].": Application Received. Submitted for Varification of Human Subject Protection Training";
  $insertSQL = sprintf("UPDATE application SET irbActionLog=%s, Status=%s, ReceivedDate=%s WHERE App_Number=%s", GetSQLValueString($newaction, "text"), GetSQLValueString($_POST['newstatus'], "text"), GetSQLValueString($today, "text"), GetSQLValueString($_POST['appNum'], "text"));
 $body = "\r\rThis email message is generated by the IRB online application program. Do not reply.\r\rAn IRB application submission was received. It is submitted for varification of Human Subject Protection Training. The application number is: ". $_POST['appNum'];
    
 	}
	
 //*********************************************************
 if($_POST['newstatus'] == "Application Submitted to IRB Chair for Review") {
 
   mysql_select_db($database_con3, $con3);
$query_Recordset3 = "SELECT `user`.Email FROM `user` where username='IRB Chair'";
$Recordset3 = mysql_query($query_Recordset3, $con3) or die(mysql_error());
$row_Recordset3 = mysql_fetch_assoc($Recordset3);
$totalRows_Recordset3 = mysql_num_rows($Recordset3);

$newaction=$newaction."IRB informed the applicant that IRB sent the applicantion for IRB Chair to review.";
  $insertSQL = sprintf("UPDATE application SET irbActionLog=%s, trainingFinished=%s, Status=%s, ChairReviewDate=%s  WHERE App_Number=%s", GetSQLValueString($newaction, "text"), GetSQLValueString($_POST['trainingFinished'], "text"), GetSQLValueString($_POST['newstatus'], "text"), GetSQLValueString($today, "text"), GetSQLValueString($_POST['appNum'], "text"));
  $subject = "IRB Application ". $_POST['appNum'].": Application Submitted to IRB Chair for Review";
  $body = "\r\rThis email message is generated by the IRB online application program. Do not reply.\r\rAn IRB application has been sent to IRB chair for review. Should your application be deemed incomplete by IRB, you will receive another email requesting additional information and/or documents. The application number is: ". $_POST['appNum']." If you have any questions, please contact IRB Chair(s) for more informaiton.";
  


do { 
$i=0;
$chair1Email[$i]=$row_Recordset3['Email'];
$to=$chair1Email[$i];
mail($to,$subject,$body);
} while ($row_Recordset3 = mysql_fetch_assoc($Recordset3));
    mysql_free_result($Recordset3);
 }
 
 //*************************************************************
 
  if($_POST['newstatus'] == "Application Submitted to Reviewers for Review") {
$newaction=$newaction."IRB informed the applicant that IRB sent the applicantion to reviewers for review.";
  $insertSQL = sprintf("UPDATE application SET irbActionLog=%s, Status=%s, ReviewDate=%s WHERE App_Number=%s", GetSQLValueString($newaction, "text"), GetSQLValueString($_POST['newstatus'], "text"), GetSQLValueString($today, "text"), GetSQLValueString($_POST['appNum'], "text"));
  $subject = "IRB Application ". $_POST['appNum'].": Application Submitted to IRB reviewers for Review";
  $body = "\r\rThis email message is generated by the IRB online application program. Do not reply.\r\rAn IRB application has been sent to IRB reviewers for review. Should your application be deemed incomplete by IRB, you will receive another email requesting additional information and/or documents. The application number is: ". $_POST['appNum'];
    
 }
 
 //*******************************************************************
  if($_POST['newstatus'] == "Request Revision") {
  $newaction = $newaction." IRB requests additional information and/or supporting documents";
  $insertSQL = sprintf("UPDATE application SET irbActionLog=%s, Status=%s, RevisionRequestDate=%s WHERE App_Number=%s", GetSQLValueString($newaction, "text"), GetSQLValueString($_POST['newstatus'], "text"), GetSQLValueString($today, "text"), GetSQLValueString($_POST['appNum'], "text"));
  $subject = "IRB Application ". $_POST['appNum'].": IRB requests additional information and/or supporting documents";
  $body = "\r\rThis email message is generated by the IRB online application program. Do not reply.\r\rYou will receive an email requsting revision for your IRB application. The application number is: ". $_POST['appNum'];
    
 }
 
 
 //**************************************************************
  if($_POST['newstatus'] == "Revision Received") {
$newaction = $newaction. "IRB Online Application informed applicant that the additional information and/or supporting documents requested was received.";
//	$from = "From: ospinfo@txstate.edu";
	$body = "\r\rThis email message is generated by the IRB online application program. Do not reply.\r\rThe additional information and/or supporting documents requested for your IRB application was received. The application number is: ". $_POST['appNum'];
    
  $insertSQL = sprintf("UPDATE application SET irbActionLog=%s,Status=%s, RevisionDate=%s WHERE App_Number=%s", GetSQLValueString($newaction, "text"), GetSQLValueString($_POST['trainingFinished'], "text"), GetSQLValueString($_POST['newstatus'], "text"), GetSQLValueString($today, "text"), GetSQLValueString($_POST['appNum'], "text"));
 }
 
 //*********************************************************
   if($_POST['newstatus'] == "Approved") {
   $newaction = $newaction. "Approved the application. IRB Online Application informed applicant that the application was approved.";
   
  $insertSQL = sprintf("UPDATE application SET irbActionLog=%s, Status=%s, ApprovedDate=%s WHERE App_Number=%s", GetSQLValueString($newaction, "text"), GetSQLValueString($_POST['trainingFinished'], "text"), GetSQLValueString($_POST['newstatus'], "text"), GetSQLValueString($today, "text"), GetSQLValueString($_POST['appNum'], "text"));
  $body = "\r\rThis email message is generated by the IRB online application program. Do not reply.\r\r"."An IRB application was approved. The application number is: ". $_POST['appNum']."\r\rApplicant can print out the approval certificate online by logging in to the web site at http://www.osp.txstate.edu/irb_new/";
  }
  
  //*************************************************************************************
    if($_POST['newstatus'] == "Applicant requested continuation") {
	   $newaction = $newaction. "IRB Administrator confirmed that an IRB project continuation request was received.";
  $insertSQL = sprintf("UPDATE application SET irbActionLog=%s, Status=%s WHERE App_Number=%s", GetSQLValueString($newaction, "text"),GetSQLValueString($_POST['trainingFinished'], "text"), GetSQLValueString($_POST['newstatus'], "text"), GetSQLValueString($_POST['appNum'], "text"));
  $body = "\r\rThis email message is generated by the IRB online application program. Do not reply.\r\r"."An IRB project continuation request was received. The application number is: ". $_POST['appNum'];
    
 }

 mysql_select_db($database_con3, $con3);
$Result1 = mysql_query($insertSQL, $con3) or die(mysql_error()); 


 
 //==================================================================
 $to = $_POST['emailAdd'];	
 //$subject = "RE: IRB Application ". $_POST['appNum'];
mail($to,$subject,$body);

//irb staff will receive the same email

$to = $_SESSION['Email'];
mail($to,$subject,$body);
  //echo "Application status updated";
 // echo "<p><a href='osp_irb_home.php'>OSP IRB Home</a>";
 

}

?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
  <meta http-equiv="Content-Type"
 content="text/html; charset=iso-8859-1">
  <title>Texas State University-San Marcos | IRB Application</title>
  <style type="text/css">
<!--
.style4 {
	font-family: Georgia, "Times New Roman", Times, serif;
	font-size: 40px;
	color: #333399;
}
.style5 {
	color: #333399;
	font-style: italic;
	font-weight: bold;
}
.style6 {
	font-family: Arial, Helvetica, sans-serif;
	color: #333399;
	font-weight: bold;
}
.style7 {
	font-family: Arial, Helvetica, sans-serif;
	font-size: 12px;
	color: #4d3319;
}
a.navbar:link {
	color: #4d3319;
	font-family: Arial, Helvetica, sans-serif;
	font-size: 10px;
	font-weight: normal;
}
a.navbar:visited {
	color: #4d3319;
	text-decoration: none;
	font-family: Arial, Helvetica, sans-serif;
	font-size: 10px;
}
a.navbar:hover {
	font-family: Arial, Helvetica, sans-serif;
	font-size: 10px;
	text-decoration: underline;
}
a.body:link {
	font-family: Arial, Helvetica, sans-serif;
	font-size: 12px;
	color: #336699;
	text-decoration: underline;
}
a.body:visited {
	font-family: Arial, Helvetica, sans-serif;
	color: #4D3319;
	text-decoration: underline;
}

a.irb:link{
font-family: Verdana, Arial, Helvetica, sans-serif;
	
	text-decoration: none;

}
a.irb:visited {
	font-family: Verdana, Arial, Helvetica, sans-serif;
	
	text-decoration: none;
}
-->
  </style>
  <style type="text/css">
<!--
body {
	background-color: #CCCCCC;
}
.style21 {
	color: #000066;
	font-size: 16px;
	font-family: Verdana, Arial, Helvetica, sans-serif;
}
.style37 {
	color: #FFFFFF;
	font-weight: bold;
}
.style38 {
	font-family: Verdana, Arial, Helvetica, sans-serif;
	font-size: small;
}
-->
  </style>
</head>
<body>
<table width="800" border="0" align="center" cellpadding="5" cellspacing="0" bgcolor="#FFFFFF" >
 <tbody>
    <tr>
      <td height="150" valign="top" width="800">
      <table width="100%" border="0" align="center" cellpadding="0" cellspacing="0" bgcolor="#FFFFFF">
 <tbody>
          <tr>
            <td rowspan="3" valign="top"><a
 href="http://www.txstate.edu"><img src="txstate_logo2.gif"
 alt="TxState" name="TxState" id="TxState" border="0"></a></td>
            <td width="113" rowspan="3" valign="top" bgcolor="#330000" class="style4"><br>  </td>
            <td width="45" height="38" bgcolor="#330000">&nbsp;</td>
            <td width="346" valign="top" bgcolor="#330000">
            <div class="style5" align="right"><font color="#336699"><br>
</font></div>            </td>
          </tr>
          <tr>          </tr>
          <tr>
            <td height="18" bgcolor="#330000"><br>            </td>
            <td valign="top" bgcolor="#330000">
            <div class="style7" align="right"><a href="LogOut.php"><span class="style37">Log
Out</span> </a></div>            </td>
          </tr>
          <tr>
            <td colspan="4" height="21" valign="top">
            <div align="center">
              <p class="style6">&nbsp;</p>
              <p><span class="style17"><a class="irb" href="index.php"><span class="style21"><strong>Institutional Review Board</strong></span></a> </p>
              <p class="style6">Online Application
              </div>            </td>
          </tr>
          <tr>
            <td colspan="4" height="19" valign="top"><hr>
              <div align="center"><span class="style38"><a href='osp_irb_home.php'>OSP IRB Home</a> | <a href="assignReviewer.php?appNum=<?php echo $appNum;?>">Assign Reviewer(s)</a> | <a href="irb_updatestatus.php?appNum=<?php echo $appNum;?>"> Update Application Status</a></span> | <a href="irb_emailApp.php?appNum=<?php echo $appNum;?>" class="style38">Email Applicant Comments/Request</a><br>
              <hr></div></td>
          </tr>
        </tbody>
      </table>
      </td>
    </tr>
</tbody></table>
<table width="800" height="300" border="0" align="center" bgcolor="#eeeeee" table>
  <tr><td>To see the change, please "Refresh" page after update status.</td></tr>
<td valign="top" >
<form id="form1" name="form1" method="post" action="<?php echo $_SERVER['PHP_SELF']."?appNum=".$appNum; ?>">
  <label>
  <div align="center" class="style38"><strong>Update Satus for this Application: 
  <?php
//$appNum = $_GET['appNum'];
echo "<p>Application Number:<font color='red'> ".$appNum."</font></p>";
echo "<p>Project Title: ".$row_Recordset1['ProjectTitle']."</p>";
?></strong></div>
  <span class="style38">
  </label>
  </span>
  <p align="center" class="style38">
    <label>    </label></p>
  <table border="0" align="center">
  <tr><td><?php if(isset($_POST['insert']) && $_POST['insert'] == "formInsert") echo "<font color='red'>Application status updated.";?></td></tr>
  <tr><td valign="top" class="style38"><p><strong>Current Status</strong>: <span class="style6"><?php echo $row_Recordset1['Status'];?></span></p>
      <p>
        <input name="trainingFinished" type="checkbox" id="trainingFinished" value="yes" 
		<?php if($row_Recordset1['trainingFinished']== "yes" || $row_Recordset1['trainingFinished']== "Yes" ) echo "Checked";?>>
        Human Subject Protection Training Finished 
        <label></label>
      </p>
      <p>&nbsp;</p></td>
  </tr>
    <tr><td class="style38">Please check one of the following to assign status to the application:</td></tr>
	<tr>
      <td width="475" class="style38"><input name="newstatus" type="radio" value="Application in Process" <?php if($row_Recordset1['Status']== "Application in Process") echo "Checked";?>/>
Application Submitted </td>
    </tr>
	
	<tr>
      <td width="475" class="style38"><input name="newstatus" type="radio" value="Application Submitted" <?php if($row_Recordset1['Status']== "Application Submitted") echo "Checked";?>/>
Application Submitted </td>
    </tr>
	
	<tr>
      <td width="475" class="style38"><input name="newstatus" type="radio" value="Application Received" <?php if($row_Recordset1['Status']== "Application Received. Submitted for Varification of Human Subject Protection Training") echo "Checked";?>/>
Application Received. Submitted for Varification of Human Subject Protection Training</td>
    </tr>
	
    <tr>
      <td class="style38"><input name="newstatus" type="radio" value="Application Submitted to IRB Chair for Review" <?php if($row_Recordset1['Status']== "Application Submitted to IRB Chair for Review") echo "Checked";?>/>
Application Submitted to IRB Chair for Review</td>
    </tr>
    <tr>
      <td class="style38"><label>
      <input name="newstatus" type="radio" value="Application Submitted to Reviewers for Review" <?php if($row_Recordset1['Status']== "Application Submitted to Reviewers for Review") echo "Checked";?>/>
Application Submitted to Reviewers for Review </label></td>
    </tr>
    <tr>
      <td class="style38"><input name="newstatus" type="radio" value="Request Revision" <?php if($row_Recordset1['Status']== "Request Revision") echo "Checked";?> />
Request Revision </td>
    </tr>
    <tr>
      <td class="style38"><label>
        <input name="newstatus" type="radio" value="Revision Received" <?php if($row_Recordset1['Status']== "Revision Received") echo "Checked";?>>
      Revision Received </label></td>
    </tr>
    <tr>
      <td class="style38"><input name="newstatus" type="radio" value="Approved" <?php if($row_Recordset1['Status']== "Approved") echo "Checked";?>/>
Application Approved</td>
    </tr>
    <tr>
      <td class="style38"><input name="newstatus" type="radio" value="Applicant Requested Continuation" <?php if($row_Recordset1['Status']== "Applicant Requested Continuation") echo "Checked";?>/>
Applicant Requested Continuation</td>
    </tr>
	<tr><td class="style38"><input name="appNum" type="hidden" value="<?php echo $appNum; ?> " /></td></tr>
	<tr><td class="style38"><input name="irbActionLog" type="hidden" value="<?php echo $row_Recordset1['irbActionLog']; ?> " /></td></tr>
    <tr><td class="style38">
	<input type="hidden" id="emailAdd" name="emailAdd" value="<?php echo $row_Recordset2['Email']; ?>">
	<input name="insert" id="insert" type="hidden" value="formInsert" /></td></tr>
      <tr><td class="style38"><label>
        <div align="center"> <br />
        <input name="Submit" type="submit" id="Submit" value="Update Application Status" />
      </div></label></td>
    </tr>
  </table>
 
  </p>
</form></td></tr></table>
</body>
</html>


<?php
mysql_free_result($Recordset2);
//

mysql_free_result($Recordset1);


?>
