<?php require_once('Connections/con3.php');
session_start();
require_once('variables/variables.php');


$restrictGoTo = "unauthorized.php";

if (!isset($_SESSION['username'])){   
 
  header("Location: ". $restrictGoTo); 
  exit;
}


if (!($_SESSION['User_Type'] == "IRB Staff")) {   
 
	if (!($_SESSION['User_Type'] == "IRB Chair")) {
   
 
  header("Location: ". $restrictGoTo); 
  exit;
  }
}

function GetSQLValueString($theValue, $theType, $theDefinedValue = "", $theNotDefinedValue = "") 
{
  $theValue = (!get_magic_quotes_gpc()) ? addslashes($theValue) : $theValue;

  switch ($theType) {
    case "text":
      $theValue = ($theValue != "") ? "'" . $theValue . "'" : "NULL";
      break;    
    case "long":
    case "int":
      $theValue = ($theValue != "") ? intval($theValue) : "NULL";
      break;
    case "double":
      $theValue = ($theValue != "") ? "'" . doubleval($theValue) . "'" : "NULL";
      break;
    case "date":
      $theValue = ($theValue != "") ? "'" . $theValue . "'" : "NULL";
      break;
    case "defined":
      $theValue = ($theValue != "") ? $theDefinedValue : $theNotDefinedValue;
      break;
  }
  return $theValue;
}

$time = date("m/d/y H:i:s");
$appNum = $_GET['appNum'];

$editFormAction = $_SERVER['PHP_SELF'];
if (isset($_SERVER['QUERY_STRING'])) {
  $editFormAction .= "?" . htmlentities($_SERVER['QUERY_STRING']);
}

if ((isset($_POST["MM_update"])) && ($_POST["MM_update"] == "form1")) {
if (!$_POST['newstatus']){
$appNum = $_POST['appNum'];
$message=$_POST['msg'];
 die("<font color='red'>You need to make a selection on the Change of Status.<br><a href='".$_SERVER['PHP_SELF']."?msg=".$message."&appNum=".$appNum."'> Back </a>");
}
	$appNum=$_POST['appNum'];
	
	//**************************************************************
	$today=date("m/d/y H:i:s");
	 $newaction=$_POST['irbActionLog']."<br><br>".$today."  ".$_SESSION['username'].":<br>";
	 //$newaction = $newaction." Email comments/request to applicant.";
	
	$msg=$_POST['prev_msg']."\r\r".$today." ".$_SESSION['username'].":\rSubject:".$_POST['subject']."\r".$_POST['msg'];
	////////////////////////////
	
		 //************************************************************
		 if($_POST['newstatus'] != "Other"){
	if($_POST['newstatus'] == "IRB Admin Requests Applicant and/or Supervising Faculty Complete HSP Training") {
	
	$ActionFlag = "Yes";
	
$newaction=$newaction."IRB administrator informed the applicant that Training on Protection of Human Research Subjects was needed.";
 $subject = "IRB Application ". $_POST['appNum'].": CITI Course completion required. DO NOT REPLY to this message.
";
  $insertSQL = sprintf("UPDATE application SET ActionFlag=%s, ActionRequestDate=%s, requestHSPActionDate = %s, irbActionLog=%s, Status=%s, ReceivedDate=%s WHERE App_Number=%s", GetSQLValueString($ActionFlag, "text"), GetSQLValueString($today, "text"), GetSQLValueString($today, "text"), GetSQLValueString($newaction, "text"), GetSQLValueString($_POST['newstatus'], "text"), GetSQLValueString($today, "text"), GetSQLValueString($_POST['appNum'], "text"));
 $body = "DO NOT REPLY TO THIS MESSAGE. This email message is generated by the IRB online application program.\r\rThe IRB Administrator has halted the submission of your IRB Application ".$_POST['appNum']." because there is no record of your completion of the CITI Course in the Protection of Human Subjects.  The CITI course can be found at the following link: \rhttps://www.citiprogram.org/default.asp?language=english\r\rPLEASE NOTE: When you complete the CITI training, a completion report will automatically be sent to the IRB Administrator, and your application will be forwarded for review. \r\rYour application is currently locked but is available as read-only.  You may log into the IRB Online Application System at any time to monitor application status. \r\rIf you have questions, please submit an IRB Inquiry form at:\r  http://www.txstate.edu/research/irb/irb_inquiry.html\r\n";
$body = $body.$emailSig;
  $to = $_POST['appEmail'];	
mail($to,$subject,$body, $headers);

    // copy to faculty
	if (strtoupper($_SESSION['User_Type']) == "STUDENT")
	{
	$subject = "This is a copy of an email message sent to your student ".$_POST['applicant'].". IRB Application ". $_POST['appNum'];
	$to = $_POST['FacultyEmail'];
	mail($to,$subject,$body, $headers);
	}

	
 	}
	
	
	//=======================================================================
	
  if($_POST['newstatus'] == "IRB Admin Requests Revision") {
  $ActionFlag = "Yes";
  $newaction = $newaction." IRB Admin requests additional information and/or supporting documents.";
  $insertSQL = sprintf("UPDATE application SET ActionFlag=%s, ActionRequestDate=%s, irbActionLog=%s, Status=%s, RevisionRequestDate=%s WHERE App_Number=%s", GetSQLValueString($ActionFlag, "text"), GetSQLValueString($today, "text"), GetSQLValueString($newaction, "text"), GetSQLValueString($_POST['newstatus'], "text"), GetSQLValueString($today, "text"), GetSQLValueString($appNum, "text"));
  $subject = "IRB Application ". $_POST['appNum'].": IRB administrator notice. DO NOT REPLY to this message.";
  $body = "DO NOT REPLY TO THIS MESSAGE. This email message is generated by the IRB online application program. \r\rThe IRB Administrator has halted the submission of your IRB Application ". $_POST['appNum'].". You will shortly be receiving an email from the IRB detailing the reason for this delay and explaining what you need to do next. Your application is currently unlocked and is available for modification. Please log into the IRB Online Application System to make revisions.\r".$irbadd."\r\rIf you have questions, please submit an IRB Inquiry form at: \rhttp://www.txstate.edu/research/irb/irb_inquiry.html\r\n";
  $body = $body.$emailSig;
  
    //applicant gets the email
 //$to = $_POST['appEmail'];	
//mail($to,$subject,$body, $headers);


 }
 
 
 //==========================================================================
   if($_POST['newstatus'] == "IRB Chair Requests Revision") {
   
   $ActionFlag = "Yes";
  $newaction = $newaction." IRB Chair requests additional information and/or supporting documents.";
  $insertSQL = sprintf("UPDATE application SET ActionFlag=%s, ActionRequestDate=%s, irbActionLog=%s, Status=%s, RevisionRequestDate=%s WHERE App_Number=%s", GetSQLValueString($ActionFlag, "text"), GetSQLValueString($today, "text"), GetSQLValueString($newaction, "text"), GetSQLValueString($_POST['newstatus'], "text"), GetSQLValueString($today, "text"), GetSQLValueString($appNum, "text"));
  $subject = "Message from IRB: IRB Application ". $_POST['appNum']." halted. DO NOT REPLY to this message.";
  $body = "DO NOT REPLY TO THIS MESSAGE. This email message is generated by the IRB online application program. \r\rThe IRB has halted the submission of your IRB Application ". $_POST['appNum']." due to an error or a request for revisions. You will shortly be receiving an email from the IRB detailing the reason for this delay and explaining what you need to do next. Your application is currently unlocked and is available for modification. Please log into the IRB Online Application System to make revisions.\r".$irbadd. "\r\rIf you have questions, please submit an IRB Inquiry form at: \rhttp://www.txstate.edu/research/irb/irb_inquiry.html\r\n";
$body = $body.$emailSig;
    //applicant gets the email
// $to = $_POST['appEmail'];	
//mail($to,$subject,$body, $headers);


 }
	
//*********************************************************
   if($_POST['newstatus'] == "Approved") {
   $newaction = $newaction. "Approved the application. IRB Online Application informed applicant that the application was approved.";
   $ActionFlag = "No";
  $insertSQL = sprintf("UPDATE application SET ActionFlag=%s,irbActionLog=%s, Status=%s, ApprovedDate=%s, lastApprovalDate=%s WHERE App_Number=%s", GetSQLValueString($ActionFlag, "text"), GetSQLValueString($newaction, "text"), GetSQLValueString($_POST['newstatus'], "text"), GetSQLValueString($today, "text"), GetSQLValueString($today, "text"), GetSQLValueString($appNum, "text"));
 $body = "\r\rThis email message is generated by the IRB online application program. Do not reply.\r\r"."Your IRB Application Number ". $_POST['appNum']." has been Approved. The approval is for a one-year period only. You may log into the IRB Online Application System to print out a detailed hard copy of your IRB approval certificate.\r".$irbadd."\r\rIf you have questions, please submit an IRB Inquiry form at: \rhttp://www.txstate.edu/research/irb/irb_inquiry.html\r\n";

  $body = $body.$emailSig;
    $subject = "Confirmation of Approval: IRB Application ". $_POST['appNum'];

     $to = $_POST['appEmail'];	
//mail($to,$subject,$body, $headers);

// copy to faculty
	if ($_POST['FacultyEmail'] !="")
	{
	$to = $_POST['FacultyEmail'];
	$subject = "This is a copy of an email message sent to your student ".$_POST['applicant'].". IRB Application ". $_POST['appNum'];
	//mail($to,$subject,$body, $headers);
	}

  }	
	
//	  mysql_select_db($database_con3, $con3);
  //$Result1 = mysql_query($insertSQL, $con3) or die(mysql_error());
 // }
	//*********************************************************
   if($_POST['newstatus'] == "Application Approved - Exempt") {
   $newaction = $newaction. "Approved the application - exempt. IRB Online Application informed applicant that the application is exempt from IRB review.";
   $ActionFlag = "No";
  $insertSQL = sprintf("UPDATE application SET ActionFlag=%s,irbActionLog=%s, Status=%s, ApprovedDate=%s, lastApprovalDate=%s WHERE App_Number=%s", GetSQLValueString($ActionFlag, "text"), GetSQLValueString($newaction, "text"), GetSQLValueString($_POST['newstatus'], "text"), GetSQLValueString($today, "text"), GetSQLValueString($today, "text"), GetSQLValueString($appNum, "text"));
 $body = "\r\rThis email message is generated by the IRB online application program. Do not reply.\r\r"."The reviewers have determined that your IRB Application Number ". $_POST['appNum']." is exempt from IRB review. The project is approved.\r\rIf you have questions, please submit an IRB Inquiry form at: \rhttp://www.txstate.edu/research/irb/irb_inquiry.html\r\n";

  $body = $body.$emailSig;
    $subject = "Confirmation of Approval: IRB Application ". $_POST['appNum'];

     $to = $_POST['appEmail'];	
//mail($to,$subject,$body, $headers);

// copy to faculty
	if ($_POST['FacultyEmail'] !="")
	{
		$subject = "This is a copy of an email message sent to your student ".$_POST['applicant'].". IRB Application ". $_POST['appNum'];
	$to = $_POST['FacultyEmail'];
	//mail($to,$subject,$body, $headers);
	}

  }	
	
	  mysql_select_db($database_con3, $con3);
  $Result1 = mysql_query($insertSQL, $con3) or die(mysql_error());
  }

////////////////// Log email message and action/////////////////
$newaction = $newaction." Email comments/request to applicant.";
  $updateSQL = sprintf("UPDATE application SET irbActionLog=%s, irbEmails=%s WHERE App_Number=%s",GetSQLValueString($newaction, "text"),
                       GetSQLValueString($msg, "text"),
                       GetSQLValueString($_POST['appNum'], "text"));

  mysql_select_db($database_con3, $con3);
  $Result1 = mysql_query($updateSQL, $con3) or die(mysql_error());
 
  
  //$headers = "From: ospinfo@txstate.edu";
	$to = $_POST['appEmail'];
//	$from = "From: ospinfo@txstate.edu";
	$body = "\r\rDO NOT REPLY TO THIS MESSAGE. This email message is generated by the IRB online application program.\r\rApplication Number: ".$_POST['appNum']."\r\r".$_POST['msg'];
    $body = $body.$emailSig;
	$subject = $_POST['subject'];

	mail($to,$subject,$body, $headers);
	
// copy to faculty
	if ($_POST['FacultyEmail'] !="")
	{
	$to = $_POST['FacultyEmail'];
	$subject = "This is a copy of an email message sent to your student ".$_POST['applicant'].". IRB Application ". $_POST['appNum'];
	mail($_POST['FacultyEmail'],$subject,$body, $headers);
	}

}

//********************************************************************************
mysql_select_db($database_con3, $con3);
$query_Recordset1 = "SELECT Status, irbActionLog,application.rev1Comments, application.rev2Comments, application.rev1Approved, application.rev2Approved, application.rev1ApprovedDate, application.rev2ApprovedDate, application.rev1ID, application.rev2ID, application.irbEmails, application.rev3ID, application.rev3Approved, application.rev3ApprovedDate, application.rev3Comments, application.App_Number, application.username, FacultyEmail FROM application where App_Number='".$appNum."'";
$Recordset1 = mysql_query($query_Recordset1, $con3) or die(mysql_error());
$row_Recordset1 = mysql_fetch_assoc($Recordset1);
$totalRows_Recordset1 = mysql_num_rows($Recordset1);

mysql_select_db($database_con3, $con3);
$query_Recordset2 = "SELECT `user`.Email, `user`.username, FirstName, LastName FROM `user` where username='".$row_Recordset1['username']."'";
$Recordset2 = mysql_query($query_Recordset2, $con3) or die(mysql_error());
$row_Recordset2 = mysql_fetch_assoc($Recordset2);
$totalRows_Recordset2 = mysql_num_rows($Recordset2);
$applicant = $row_Recordset2['FirstName']." ".$row_Recordset2['LastName'];
?>


<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
  <meta http-equiv="Content-Type"
 content="text/html; charset=iso-8859-1">
  <title>Texas State University-San Marcos | IRB Online Application</title>
  <LINK href="irbstyle.css" rel="stylesheet" type="text/css">


  <style type="text/css">
<!--
.style43 {font-size: large}
-->
  </style>

</head>

  
  <script>
function ValidateRadio()
{

}
  </script>
<body>
<table width="800" border="0" align="center" cellpadding="0" cellspacing="0" bgcolor="#FFFFFF" >
  <tr><td>
<table width="800" border="0" align="center" cellpadding="0" cellspacing="0" background="tbbg.gif" >
<tbody>
   <tr background="tbbg.gif">
            <td width="552" valign="top"><p align="left" class="style6 style24"><img src="banner2.jpg" width="550" height="160"></td>
            <td width="248" valign="middle" background="tbbg.gif"><p align="center"> <a class="tsu" href="http://www.txstate.edu">Texas State University</a></p>
              <p align="center"><a class="irbhome" href="index.php" ><span class="style43">I</span>nstitutional <span class="style43">R</span>eview <span class="style43">B</span>oard <span class="style43">O</span>nline <span class="style43">A</span>pplication </p>
           
            </p>
            </span></td>
   </tr>
</tbody></table>
<table width="800" border="0" align="center" bgcolor="#ffffff">
          <tr>
            <td colspan="3" height="19" valign="top" bgcolor="#000000">
			  <div align="center"><span class="style46"><a href='osp_irb_home.php' class="irb">My IRB Home</a> </span><span class="style39">|</span><span class="style46"> <a href="appSummary_irb.php?appNum=<?php echo $appNum;?>" class="irb">Review Application Data</a> </span><span class="style39">|</span><span class="style46"> <a href="statSummary.php?appNum=<?php echo $appNum;?>" class="irb">Summary of Status, Evaluations and Action Logs</a></span><br>
			  <a href="assignReviewer.php?appNum=<?php echo $appNum;?>" class="irb">Assign/Change Reviewer(s)</a> </span><span class="style39">|</span><span class="style46"> <a href="irb_updatestatus.php?appNum=<?php echo $appNum;?>" class="irb"> Update Application Status</a> </span><span class="style39">|</span> <a href="irb_emailApp.php?appNum=<?php echo $appNum;?>" class="irb">Send Comments/Requests to Applicant </a> <span class="style39">|</span> <a href="LogOut.php" class="irb">Log Out</a> </div></td>
          </tr>
  </tbody>
      </table>
      </td>
  </tr>
    <tr>
      <td valign="top"><div align="center">
        <p>&nbsp;</p>
        <p><strong>SEND COMMENTS OR REQUESTS TO THE APPLICANT</strong></p>
        <p>Application Number: <?php echo $appNum;?> 
        <hr>
      </div>
        <table border="1" cellpadding="6" cellspacing="-1" width="100%">
	  
	  <tr><?php 
	  if ($row_Recordset1['rev1ID']){
	  ?>
	  
	  <td width="34%" valign="top">Reviewer 1: 
<?php	  mysql_select_db($database_con3, $con3);
	$query_revName = "SELECT `user`.FirstName, `user`.LastName FROM `user` where username='".$row_Recordset1['rev1ID']."'";
	$revNameRecordset = mysql_query($query_revName, $con3) or die(mysql_error());
	$row_revNameRecordset = mysql_fetch_assoc($revNameRecordset);
	$totalRows_revNameRecordset = mysql_num_rows($revNameRecordset);

	  
	  echo $row_revNameRecordset['FirstName']." ".$row_revNameRecordset['LastName']; 
	  
	  ?>
	  <br>
	    Approved? <?php echo $row_Recordset1['rev1Approved']; ?><br>
		Date of Approval: <?php if (strtoupper($row_Recordset1['rev1Approved']) == "YES")
	    echo $row_Recordset1['rev1ApprovedDate']; ?>
	       <br>
	       <br> Comments:<br>
	        <?php 
			 if ($row_Recordset1['rev3ID'])
			 
	  			echo "<br><textarea cols='25' rows='6'>";
	  		else
	  			echo "<br><textarea cols='40' rows='6'>";
			echo $row_Recordset1['rev1Comments']; 
			echo "</textarea>";
			mysql_free_result($revNameRecordset);
			}
			echo "</td>"; ?></p>
	      
	  <?php   if ($row_Recordset1['rev2ID']){?><td width="34%" valign="top">Reviewer 2: 
	<?php  mysql_select_db($database_con3, $con3);
	$query_revName = "SELECT `user`.FirstName, `user`.LastName FROM `user` where username='".$row_Recordset1['rev2ID']."'";
	$revNameRecordset = mysql_query($query_revName, $con3) or die(mysql_error());
	$row_revNameRecordset = mysql_fetch_assoc($revNameRecordset);
	$totalRows_revNameRecordset = mysql_num_rows($revNameRecordset);

	  
	  echo $row_revNameRecordset['FirstName']." ".$row_revNameRecordset['LastName']; 
	  
	  
	  ?><br>
	  Approved? 
	  <?php echo $row_Recordset1['rev2Approved']; ?>
	  <br>Date of Approval: <?php if (strtoupper($row_Recordset1['rev2Approved']) == "YES")
	  echo $row_Recordset1['rev2ApprovedDate']; ?>
	  <br>
	<br>Comments:	<br>
	  <?php 
	  if ($row_Recordset1['rev3ID'])
	  	echo "<br><textarea cols='25' rows='6'>";
	  else
	  echo "<br><textarea cols='40' rows='6'>";
	  echo $row_Recordset1['rev2Comments']; 
	  echo "</textarea>";
	  mysql_free_result($revNameRecordset);
	  }
	echo "</td>"; ?>
	   
	 <?php if ($row_Recordset1['rev3ID']){?>
	  <td width="32%" valign="top"> Reviewer 3: <?php   
	   mysql_select_db($database_con3, $con3);
	$query_revName = "SELECT `user`.FirstName, `user`.LastName FROM `user` where username='".$row_Recordset1['rev3ID']."'";
	$revNameRecordset = mysql_query($query_revName, $con3) or die(mysql_error());
	$row_revNameRecordset = mysql_fetch_assoc($revNameRecordset);
	$totalRows_revNameRecordset = mysql_num_rows($revNameRecordset);

	  
	  echo $row_revNameRecordset['FirstName']." ".$row_revNameRecordset['LastName']; 
	  
	  
	  ?><br>
	  Approved? <?php echo $row_Recordset1['rev3Approved']; ?>
	  <br>
	  <?php if (strtoupper($row_Recordset1['rev3Approved']) == "YES")
	  echo "Date of Approval: ".$row_Recordset1['rev3ApprovedDate']; ?>
	<br><br>Comments:<br>
	  <?php 
	  echo "<br><textarea cols='25' rows='6'>";
	  echo $row_Recordset1['rev3Comments']."</textarea></td>"; 
	  mysql_free_result($revNameRecordset);
	  }
	  
	//  else echo "<td> No Reviewer Assigned</td>";
	  ?>	  </tr></table></td></tr><tr><td>
	  
	  
	  
	  <table width="799" cellspacing="6">
	    <tr><td width="100%" >
 <tr>
   <td class="style38"><strong>Status Change Applied </strong></td>
 </tr>
		        <form name="form1" id="form1" action="<?php echo $editFormAction; ?>" method="POST" onSubmit="ValidateRadio()" >
     <tr> <td class="style38"><input name="newstatus" id="newstatus" type="radio" value="IRB Admin Requests Revision" <?php if($row_Recordset1['Status']== "IRB Admin Requests Revision") echo "Checked";?> />
IRB Admin Requests Revision </td>
    </tr>
	   
	<tr>
      <td class="style38"><input name="newstatus" id="newstatus" type="radio" value="IRB Admin Requests Applicant and/or Supervising Faculty Complete HSP Training" <?php if($row_Recordset1['Status']== "IRB Admin Requests Applicant and/or Supervising Faculty Complete HSP Training") echo "Checked";?> />
IRB Admin Requests Applicant to Complete HSP Training </td>
    </tr>
 
	    <tr>
      <td class="style38"><input name="newstatus" id="newstatus" type="radio" value="IRB Chair Requests Revision" <?php if($row_Recordset1['Status']== "IRB Chair Requests Revision") echo "Checked";?> />
IRB Chair Requests Revision </td>
    </tr>
	 <tr> <td class="style38"><input name="newstatus" id="newstatus" type="radio" value="Application Approved - Exempt" <?php if($row_Recordset1['Status']== "Application Approved - Exempt") echo "Checked";?> />
Application Approved - Exempt</td>
    </tr>
	   <tr>
      <td class="style38"><input name="newstatus" id="newstatus" type="radio" value="Approved" <?php if($row_Recordset1['Status']== "Approved") echo "Checked";?>/>
Application Approved</td>
    </tr>
	      <td class="style38"><input name="newstatus" id="newstatus" type="radio" value="Other"/>
None of the Above</td>
    </tr>
	<tr><td>
     
	          <?php if($row_Recordset1['irbEmails'] !=""){?>
	         <p align="center"><hr> <div align="left"><strong>Messages Sent</strong>
	         <br>
	           
	           <input name="prev_msg" type="hidden" id="prev_msg" value="<?php echo $row_Recordset1['irbEmails']; ?>">
	           <?php 
		 echo "<br><textarea cols='80' rows='10'>";
		 
		 echo $row_Recordset1['irbEmails']; 
		 echo "</textarea><br>";
		 ?>
	            <?php } ?>
	           </p>
	           </div>
	         </div>
	         <hr>
	         <div align="left"><strong>New Message</strong> </div>
	      <br>
	     <div align="center">
	     <div align="left">Subject:
	       <input name="subject" type="text" size="80" value="IRB Application <?php echo $appNum;?>">
          </div>
	       </div>
	     </label>       
	   <p align="left">              <br>
	     <textarea name="msg" cols="80" rows="8"><?php echo $_GET['msg'];?></textarea>
	     <input type="hidden" name="irbActionLog" ID="irbActionLog" value="<?php echo $row_Recordset1['irbActionLog'];?>">
	      <input type="hidden" name="appNum" ID="appNum" value="<?php echo $appNum;?>">
	     <br> 
<input name="submit1" type="submit" value="Send Message and Update Status" >
	      <input type="hidden" name="appEmail" value="<?php echo $row_Recordset2['Email']; ?>">
		  <input type="hidden" name="FacultyEmail" value="<?php echo $row_Recordset1['FacultyEmail']; ?>">
		  		  <input type="hidden" name="applicant" value="<?php echo $applicant; ?>">
		  
	      <input type="hidden" name="MM_update" value="form1">
	      <input type="hidden" name="appNum" value="<?php echo $appNum;?>">
        </form>
	  
	  
	  	</table></td></tr><tr><td><table style="width: 100%;" border="0" cellpadding="0" cellspacing="0">
           
                <tr>
                  <td><hr></td>
                </tr>
             
    <tr>
      <td style="vertical-align: top; height: 60px;"><?php include("footer.php"); ?></td>
    </tr>
</table></td></tr>
		</table></td>
    </tr></table>
	
	  
</body>
</html>
<?php
mysql_free_result($Recordset1);

mysql_free_result($Recordset2);
?>
