<?php require_once('Connections/con3.php');
session_start();
require_once('variables/variables.php');


$restrictGoTo = "unauthorized.php";

if (!isset($_SESSION['username'])){   
 
  header("Location: ". $restrictGoTo); 
  exit;
}

/////////////////////////////////////////////////////////////////

$appNum=$_POST["appNum"];
$today=date("m/d/y H:i:s");

if ($_POST['appsub'] == "Application Submitted"){
if($_POST['doc'] == "none")
{

$query_Recordset0 = "SELECT username from application where App_Number='".$appNum."'";
$Recordset0 = mysql_query($query_Recordset0, $con3) or die(mysql_error());
$row_Recordset0 = mysql_fetch_assoc($Recordset0);
$totalRows_Recordset0 = mysql_num_rows($Recordset0);
$app=$Recordset0['username'];

mysql_free_result($Recordset0);
$query_Recordset0 = "SELECT Email from user where username='".$app."'";
$Recordset0 = mysql_query($query_Recordset0, $con3) or die(mysql_error());
$row_Recordset0 = mysql_fetch_assoc($Recordset0);
$totalRows_Recordset0 = mysql_num_rows($Recordset0);
$app=$Recordset0['Email'];

$to = $app;
	$subject = "IRB Application Failed Submitted: ".$_POST['appNum'];
$body = "\rDO NOT REPLY TO THIS MESSAGE. This email message is generated by the IRB online application program. \r\rYou did not upload any supporting document. At minimum, your application requires a synopsis. The template is available at the IRB web site. In addition, please refer to the web site for Requirements Checklist for Consent Forms.\r\nhttp://www.txstate.edu/research/irb/";
	$body = $body.$emailSig;
	mail($to,$subject,$body, $headers);
	mysql_free_result($Recordset0);
////////////////////
header("Location: ". "uploader.php?appNum=".$appNum); 
}
else
{
mysql_select_db($database_con3, $con3);
$query_Recordset0 = "SELECT username, irbActionLog, FacultyEmail from application where App_Number='".$appNum."'";
$Recordset0 = mysql_query($query_Recordset0, $con3) or die(mysql_error());
$row_Recordset0 = mysql_fetch_assoc($Recordset0);
$totalRows_Recordset0 = mysql_num_rows($Recordset0);
$irbActionLog=$row_Recordset0['irbActionLog'];
$FacultyEmail=$row_Recordset0['FacultyEmail'];
$applicant = $row_Recordset0['username'];
///////////////////////////////////

mysql_select_db($database_con3, $con3);
$query_Recordset1 = "SELECT `user`.Email, `user`.User_Type FROM `user` where User_Type='IRB Staff'";
$Recordset1 = mysql_query($query_Recordset1, $con3) or die(mysql_error());
$row_Recordset1 = mysql_fetch_assoc($Recordset1);
$totalRows_Recordset1 = mysql_num_rows($Recordset1);

//////////////////////Applicant Name 
mysql_select_db($database_con3, $con3);
$query_Recordset2 = "SELECT FirstName, LastName FROM `user` where username='".$applicant."'";
$Recordset2 = mysql_query($query_Recordset2, $con3) or die(mysql_error());
$row_Recordset2 = mysql_fetch_assoc($Recordset2);
$totalRows_Recordset2 = mysql_num_rows($Recordset2);
$applicantName = $row_Recordset2['FirstName']." ".$row_Recordset2['LastName'];
mysql_free_result($Recordset2);

  ///////// notice to IRB staff
	$to = $row_Recordset1['Email'];
	$subject = "IRB Application Submitted: ".$_POST['appNum'];
$body = "\rDO NOT REPLY TO THIS MESSAGE. This email message is generated by the IRB online application program. \r\rAn IRB Application has been submitted for review. The Application number is ".$_POST['appNum']. ".\r\rYou may log in to the IRB Online Application System to review the application:\r".$irbadd."?appNum=".$_POST['appNum']."\r\n";
	$body = $body.$emailSig;
	mail($to,$subject,$body, $headers);
    
	/////////////////////Confirmation to applicant
if (strtoupper($_SESSION['User_Type']) != "STUDENT"){	
$body = "\rDO NOT REPLY TO THIS MESSAGE. This email message is generated by the IRB online application program. Do not reply.\r\rYour IRB Application has been submitted for review. The Application number is ".$_POST['appNum']. ".\r\rAfter IRB admin verifies that you have completed the CITI Human Subjects Protection Training program, your application will be forwarded for assignment to reviewers. \r\rWhile under review, your application is locked but is available as read-only.  You may log in to the IRB Online Application System at any time to monitor review status.\r". $irbadd."?appNum=".$_POST['appNum']."\r\nYou will receive notification emails when your application status changes.  If the IRB requests changes or additions, your application will be unlocked and you will be able to modify it. \r\rIf you have questions, please submit an IRB Inquiry form at: \rhttp://www.txstate.edu/research/irb/irb_inquiry.html\r\n";
	
	$body = $body.$emailSig;
	
	$subject = "IRB Application Submission Confirmation: ".$_POST['appNum'];
	$to=$_SESSION['Email'];
	mail($to,$subject,$body, $headers);
	}
	// copy to faculty
	if (strtoupper($_SESSION['User_Type']) == "STUDENT")
	{
	$body = "\rDO NOT REPLY TO THIS MESSAGE. This email message is generated by the IRB online application program. Do not reply.\r\rYour IRB Application has been submitted for review. The Application number is ".$_POST['appNum']. ". Faculty members' certifications are required for all student applications. IRB admin will review the application after the application has been certified by the faculty member. \r\rAfter IRB admin verifies that you have completed the CITI Human Subjects Protection Training program, your application will be forwarded for assignment to reviewers. \r\rWhile under review, your application is locked but is available as read-only.  You may log in to the IRB Online Application System at any time at:\r". $irbadd."?appNum=".$_POST['appNum']."\r\nYou will receive notification emails when your application status changes.  If the IRB requests changes or additions, your application will be unlocked and you will be able to modify it. \r\rIf you have questions, please submit an IRB Inquiry form at: \rhttp://www.txstate.edu/research/irb/irb_inquiry.html\r\n";
		
	$subject = "IRB Application Submission Confirmation: ".$_POST['appNum'];
	$to=$_SESSION['Email'];
	mail($to,$subject,$body, $headers);
	$to = $FacultyEmail;
	
 $subject = "Please approve your student's application - ".$applicantName."- IRB Application ". $_POST['appNum'];
	mail($to,$subject,$body, $headers);
	}
////////////////////
$irbActionLog=$irbActionLog."<p>".$today." ".$_SESSION['username'].":<br> Submitted the application.";

mysql_select_db($database_con3, $con3);
$query_update = "update application set irbActionLog = '".$irbActionLog."', ActionFlag = 'No', submissionFinishedDate = '".$today."', Status = 'Application Submitted' where App_Number='". $_POST['appNum']."'";
$result = mysql_query($query_update, $con3) or die(mysql_error());
//////////////////////////
$query = "select * from reviewlog where (appNum='".$appNum."' && reviewNum = '1')";
mysql_select_db($database_con3, $con3);
$result = mysql_query($query, $con3);
$numrows = mysql_num_rows($result);
if ($numrows==0){
$insertSQL = "insert into reviewlog (appNum, reviewNum) values ('".$appNum."', '1')";

$result1 = mysql_query($insertSQL, $con3) or die(mysql_error());
}
mysql_free_result($result);
mysql_free_result($Recordset0);
mysql_free_result($Recordset1);
 header("Location: ". $_SESSION['myhome']); 
exit;
}
}
?>