<?php require_once('Connections/con3.php'); ?><?php require_once('Connections/con3.php');
session_start();

$restrictGoTo = "unauthorized.php";

if (!isset($_SESSION['username'])){   
 
  header("Location: ". $restrictGoTo); 
  exit;
}

/////////////////////////////////////////////////////////////////

$appNum=$_GET["appNum"];
if ($_POST["fileUp"]){
$appNum = $_POST['appNum'];
}
if ($_POST["fileUp"]){
if ($_FILES["file"]["error"] > 0)
  {
  echo "Error: " . $_FILES["file"]["error"] . "<br />";
  }
else
  {
  echo "File Uploaded: " . $_FILES["file"]["name"] . "<br />";
  echo "Type: " . $_FILES["file"]["type"] . "<br />";
  echo "Size: " . ($_FILES["file"]["size"] / 1024) . " Kb<br />";
  //echo "Temp File Folder Used: " . $_FILES["file"]["tmp_name"];
  echo "<br>";
  }

$dir="appdoc/".$appNum;
if (!is_dir($dir)) 
{ 
mkdir($dir); 
} 
//echo $dir;

     
  move_uploaded_file($_FILES["file"]["tmp_name"], $dir."/". $_FILES["file"]["name"]);
     echo "Stored as: " .$dir."/". $_FILES["file"]["name"];
     
	//  echo "<br><a href='applicant_home.php'>Back to Application Home</a><br>";
}

if ($_POST['Submit2'] == "Application Revision Finished"){
mysql_select_db($database_con3, $con3);
$query_Recordset1 = "SELECT `user`.Email, `user`.User_Type FROM `user` where User_Type='IRB Chair'";
$Recordset1 = mysql_query($query_Recordset1, $con3) or die(mysql_error());
$row_Recordset1 = mysql_fetch_assoc($Recordset1);
$totalRows_Recordset1 = mysql_num_rows($Recordset1);


  do{
	$to = $row_Recordset1['Email'];
//	$from = "From: ospinfo@txstate.edu";
	$body = "\r\rThis email message is generated by the IRB online application program. Do not reply.\r\rApplication revision finished. Application number: ".$_POST['appNum'];
    
	$subject = "RE: Application Revision Finished";

	mail($to,$subject,$body);
 }while($row_Recordset1 = mysql_fetch_assoc($Recordset1));
 
 //Email to reviewers
 if ($_POST['rev1Email'])
 {
 $to = $_POST['rev1Email'];
//	$from = "From: ospinfo@txstate.edu";
	$body = "\r\rThis email message is generated by the IRB online application program. Do not reply.\r\rApplication revision finished. Application number: ".$_POST['appNum'];
    
	$subject = "RE: Application Revision Finished";

	mail($to,$subject,$body);
 
 }
 
  if ($_POST['rev2Email'])
 {
 $to = $_POST['rev2Email'];
//	$from = "From: ospinfo@txstate.edu";
	$body = "\r\rThis email message is generated by the IRB online application program. Do not reply.\r\rApplication revision finished. Application number: ".$_POST['appNum'];
    
	$subject = "RE: Application Revision Finished";

	mail($to,$subject,$body);
 
 }
 
  if ($_POST['rev3Email'])
 {
 $to = $_POST['rev3Email'];
//	$from = "From: ospinfo@txstate.edu";
	$body = "\r\rThis email message is generated by the IRB online application program. Do not reply.\r\rApplication revision finished. Application number: ".$_POST['appNum'];
    
	$subject = "RE: Application Revision Finished";

	mail($to,$subject,$body);
 
 }
 
 
 
 header("Location: ". "applicant_home.php"); 
exit;
}
?>
<?php
mysql_select_db($database_con3, $con3);
$query_Recordset2 = "SELECT application.rev1ID, application.rev2ID, application.rev3ID FROM application where App_Number='".$appNum."'";
$Recordset2 = mysql_query($query_Recordset2, $con3) or die(mysql_error());
$row_Recordset2 = mysql_fetch_assoc($Recordset2);
$totalRows_Recordset2 = mysql_num_rows($Recordset2);

 $reviewerID1  = $row_Recordset2['rev1ID'];
   if($reviewerID1){ 
   if (!get_magic_quotes_gpc()){$reviewerID1=addslashes($reviewerID1);}}
  // echo "Reviewers: ".$reviewerIDs."<p>";
//$arrReviewerID = explode(",", $reviewerIDs);
//echo "Number of reviewer:".count($arrReviewerID);

$reviewerID2  = $row_Recordset2['rev2ID'];
if($reviewerID2){ 
if (!get_magic_quotes_gpc()){$reviewerID2=addslashes($reviewerID2);}}

$reviewerID3  = $row_Recordset2['rev3ID'];
if($reviewerID3){ 
if (!get_magic_quotes_gpc()){$reviewerID3=addslashes($reviewerID3);}}

////////////////////////////////////////////
if($reviewerID1){ 
$sqlRev=sprintf("SELECT Email FROM user where username='%s'", $reviewerID1);

$rev = mysql_query($sqlRev, $con) or die(mysql_error());
$rs_rev = mysql_fetch_assoc($rev);
//echo "<br>Reviewer Name: ".$rs_rev['FirstName']."&nbsp;".$rs_rev['LastName']." / ";
$rev1Email = $rs_rev['Email'];
mysql_free_result($rev);
}

if($reviewerID2){ 
$sqlRev=sprintf("SELECT Email FROM user where username='%s'", $reviewerID2);

$rev = mysql_query($sqlRev, $con) or die(mysql_error());
$rs_rev = mysql_fetch_assoc($rev);
//echo "<br>Reviewer Name: ".$rs_rev['FirstName']."&nbsp;".$rs_rev['LastName']." / ";
$rev2Email = $rs_rev['Email'];
mysql_free_result($rev);
}

if($reviewerID3){ 
$sqlRev=sprintf("SELECT Email FROM user where username='%s'", $reviewerID3);

$rev = mysql_query($sqlRev, $con) or die(mysql_error());
$rs_rev = mysql_fetch_assoc($rev);
//echo "<br>Reviewer Name: ".$rs_rev['FirstName']."&nbsp;".$rs_rev['LastName'];
$rev3Email = $rs_rev['Email'];
mysql_free_result($rev);
}
?><html><head><title></title>
</head><body>
<p><a href="applicant_home.php">Applicant Home</a></p>
<p align="center"><strong>Upload Supporting Document(s) </strong></p>
<form action="uploadRevision_applicant.php" method="post" enctype="multipart/form-data" name="form1" id="form1"> 
<input type="hidden" name="fileUp" value="yes" id="fileUp">
<input type="hidden" name="appNum" value="<?php echo $appNum; ?>" id="appNum">
  <label>More File to Upload:<br> 
  <input type="file" name="file" /> <input type="submit" name="Submit" value="Upload File" /></form>
  </label>
  <p>
</p>
   <p>If you have finished your application revision submission, click the &quot;Application Revision Finished&quot; button. 
     <label><form method="post" action="uploadRevision_applicant.php" name="form2" id="form2">
	 <input type="hidden" name="appNum" value="<?php echo $appNum; ?>" id="appNum">
	 <input type="hidden" name="rev1Email" value="<?php echo $rev1Email; ?>" id="appNum">
	 <input type="hidden" name="rev2Email" value="<?php echo $rev2Email; ?>" id="appNum">
	 <input type="hidden" name="rev3Email" value="<?php echo $rev3Email; ?>" id="appNum">
     <input type="submit" name="Submit2" value="Application Revision Finished"></form>
     </label>
   </p>
   </form>
	
  </body> 
</html>
<?php
mysql_free_result($Recordset2);
?>
